### ISSUE TITLE
panic in metrics

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1349]
2019/08/07 21:06:12 HTTP server listen on port: 19000
2019/08/07 21:06:12 Supported API:
2019/08/07 21:06:12 /ping        I'm alive!
2019/08/07 21:06:12 /init        Start Benchmark/Txgen
2019/08/07 21:10:27 Init Handler
2019/08/07 21:10:27 running instance
2019/08/07 21:10:27 Command running ./harmony [-ip 52.10.38.210 -port 9000 -log_folder ../tmp_log/log-20190807.210502 -bootnodes /ip4/54.213.43.194/tcp/9867/p2p/QmZJJx6AdaoEkGLrYG4JeLCKeCKDjnFz2wfHNHxAqFSGA9,/ip4/100.26.90.187/tcp/9867/p2p/Qmdfjtk6hPoyrH1zVD9PEH4zfWLo38dP2mDvvKXfh3tnEv,/ip4/13.113.101.219/tcp/9867/p2p/QmQayinFSgMMw5cSpDUiD9pQ2WeP6WNmGxpZ6ou3mdVFJX,/ip4/99.81.170.167/tcp/9867/p2p/QmRVbTpEYup8dSaURZfF6ByrMTSKa4UyUzJhSjahFzRqNj -min_peers 101 -blspass file:blsnopass.txt -blskey_file b681e471d81c54386931eb6bfa1546f64d09cdf6ff1e19ed427ab4433bc053f42167b09344363dc4022c7fe2e7b6d419.key -log_conn -network_type=pangaea -dns=false]
2019/08/10 23:35:59 Stderr: panic: counter cannot decrease in value

goroutine 114 [running]:
github.com/prometheus/client_golang/prometheus.(*counter).Add(0xc0003f4380, 0xbff0000000000000)
   /home/ec2-user/go/pkg/mod/github.com/prometheus/client_golang@v0.9.2/prometheus/counter.go:89 +0x134
github.com/harmony-one/harmony/api/service/metrics.UpdateBlockHeight(0x7fa7)
   /data/harmony/api/service/metrics/service.go:166 +0x71
github.com/harmony-one/harmony/node.(*Node).UpdateBlockHeightForMetrics(0xc0006dcc00, 0x7fa8, 0x5d4f5401)
   /data/harmony/node/node_metrics.go:19 +0x14d
github.com/harmony-one/harmony/node.(*Node).CollectMetrics(0xc0006dcc00)
   /data/harmony/node/node_metrics.go:69 +0xf7
created by github.com/harmony-one/harmony/node.New
   /data/harmony/node/node.go:391 +0x7b9
2019/08/10 23:35:59 Command finished with error: exit status 2

**Comment by LeoHChen** [comment]
This is on Pangaea network.
