### ISSUE TITLE
Explorer keeps crashing

### ISSUE THREAD

**Issue by xChickens** [harmony-one/harmony#1475]
```
(node:27140) UnhandledPromiseRejectionWarning: Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.send (/home/ec2-user/projects/harmony-dashboard-backend/node_modules/ws/lib/websocket.js:314:19)
    at B.default.getNodeCount.v.clients.forEach.e (/home/ec2-user/projects/harmony-dashboard-backend/dist/main.js:1:7475)
    at Set.forEach (<anonymous>)
    at Promise.all.then.e (/home/ec2-user/projects/harmony-dashboard-backend/dist/main.js:1:7461)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:27140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise wh
ich was not handled with .catch(). (rejection id: 1)
(node:27140) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero ex
it code.
(node:27140) UnhandledPromiseRejectionWarning: Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.send (/home/ec2-user/projects/harmony-dashboard-backend/node_modules/ws/lib/websocket.js:314:19)
    at a.every.v.clients.forEach.e (/home/ec2-user/projects/harmony-dashboard-backend/dist/main.js:1:7166)
    at Set.forEach (<anonymous>)
    at Promise.all.then.e (/home/ec2-user/projects/harmony-dashboard-backend/dist/main.js:1:7152)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:27140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise wh
ich was not handled with .catch(). (rejection id: 2)
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x8f9d10 node::Abort() [node]
 2: 0x8f9d5c  [node]
 3: 0xaffd0e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xafff44 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xef4152  [node]
 6: 0xf0396f v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
 7: 0xecc9c6 v8::internal::Factory::AllocateRawArray(int, v8::internal::PretenureFlag) [node]
 8: 0xecd24a v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Heap::RootListIndex, int, v8::internal::Object*, v8::internal::PretenureFlag) [node]
 9: 0xed9c31 v8::internal::Factory::NewJSArrayStorage(v8::internal::Handle<v8::internal::JSArray>, int, int, v8::internal::ArrayStorageAllocationMode) [node]
10: 0xed9f2c v8::internal::Factory::NewJSArray(v8::internal::ElementsKind, int, int, v8::internal::ArrayStorageAllocationMode, v8::internal::PretenureFlag) [node]
11: 0xe93361 v8::internal::ElementsAccessor::Concat(v8::internal::Isolate*, v8::internal::Arguments*, unsigned int, unsigned int) [node]
12: 0xb8f349  [node]
13: 0xb98a48 v8::internal::Builtin_ArrayConcat(int, v8::internal::Object**, v8::internal::Isolate*) [node]
14: 0x28be881dbf7d
sh: line 1: 27140 Aborted                 node dist/main.js > log
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! harmony-dashboard-backend@1.0.0 serve: `node dist/main.js > log`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the harmony-dashboard-backend@1.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2019-08-31T01_23_05_554Z-debug.log
```

**Comment by lzl124631x** [comment]
It's an OOM error. It will be solved by my firestore update.
