### ISSUE TITLE
Transaction segmentation error

### ISSUE THREAD

**Issue by xChickens** [harmony-one/harmony#1527]
```Transaction Id for shard 0: 0xbcc2749edd652104429762830bd14554ca5f0d9932ea178ee5d7e247204ef726
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x168 pc=0xc942ad]

goroutine 1233 [running]:
github.com/harmony-one/harmony/node.(*Node).pingMessageHandler(0xc0003ba000, 0xc00015c467, 0xcf, 0xd9, 0xc0007286c0, 0x22, 0xc0002188a0)
        /mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:587 +0xabd
github.com/harmony-one/harmony/node.(*Node).messageHandler(0xc0003ba000, 0xc00015c465, 0xd1, 0xdb, 0xc0007286c0, 0x22)
        /mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:181 +0xa01
created by github.com/harmony-one/harmony/node.(*Node).ReceiveClientGroupMessage
        /mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:98 +0x177
```

Somewhat common, when running ./wallet.sh transfer, many people (on Pangaea) get this error right after transaction ID is printed.

**Comment by denniswon** [comment]
is this s3 branch?

**Comment by denniswon** [comment]
Do you know when this issue started happening? @LeoHChen is https://github.com/harmony-one/harmony/pull/1513 related? (merged to master already, but not in s3)

**Comment by xChickens** [comment]
This is s3, it's probably related. We might try a relaunch of Pangaea on master.

**Comment by LeoHChen** [comment]
This is duplicated, and fixed by https://github.com/harmony-one/harmony/issues/1512
