### ISSUE TITLE
Shard 3 Leader process crash after receiving bad block (attempted rollback)

### ISSUE THREAD

**Issue by xChickens** [harmony-one/harmony#1590]
```
{"level":"debug","port":"9000","ip":"3.19.234.243","caller":"/data/harmony-main/consensus/consensus_v2.go:808","time":"2019-09-12T22:02:16.377186444Z","message":"[OnCommitted] Receive committed message"}
{"level":"info","port":"9000","ip":"3.19.234.243","numShards":128,"caller":"/data/harmony-main/core/rawdb/accessors_chain.go:477","time":"2019-09-12T22:02:16.387545769Z","message":"wrote last commits"}
{"level":"debug","port":"9000","ip":"3.19.234.243","MsgViewID":4081,"MsgBlockNum":4081,"caller":"/data/harmony-main/consensus/consensus_v2.go:872","time":"2019-09-12T22:02:16.387570545Z","message":"[OnCommitted] Committed message added"}
{"level":"debug","port":"9000","ip":"3.19.234.243","MsgBlockNum":4081,"caller":"/data/harmony-main/consensus/consensus_v2.go:881","time":"2019-09-12T22:02:16.387582854Z","message":"[OnCommitted] out of sync"}
{"level":"info","port":"9000","ip":"3.19.234.243","epoch":1,"caller":"/data/harmony-main/core/resharding.go:227","time":"2019-09-12T22:02:16.638574117Z","message":"Get Shard State of Epoch."}
{"level":"debug","port":"9000","ip":"3.19.234.243","caller":"/data/harmony-main/consensus/consensus_v2.go:154","time":"2019-09-12T22:02:16.66067292Z","message":"[OnAnnounce] Receive announce message"}
{"level":"debug","port":"9000","ip":"3.19.234.243","MsgViewID":4082,"MsgBlockNum":4082,"caller":"/data/harmony-main/consensus/consensus_v2.go:250","time":"2019-09-12T22:02:16.66604096Z","message":"[OnAnnounce] Announce message Added"}
{"level":"error","port":"9000","ip":"3.19.234.243","error":"missing trie node f474e58237ebdd30f6c2732e5048ca68feff8fbaf280bb3b1b68c450fb134785 (path )","caller":"/data/harmony-main/api/service/syncing/syncing.go:552","time":"2019-09-12T22:02:16.950497485Z","message":"[SYNC] Error adding new block to blockchain 3980 3"}
{"level":"debug","port":"9000","ip":"3.19.234.243","block":{"ReceivedAt":"0001-01-01T00:00:00Z","ReceivedFrom":null},"caller":"/data/harmony-main/api/service/syncing/syncing.go:554","time":"2019-09-12T22:02:16.95053459Z","message":"[SYNC] Rolling back current block!"}
{"level":"debug","port":"9000","ip":"3.19.234.243","caller":"/data/harmony-main/api/service/syncing/syncing.go:753","time":"2019-09-12T22:02:17.047050849Z","message":"[SYNC] Node is Not in Sync (isBeacon: false, ShardID: 3, otherHeight: 4080, currentHeight: 3978)"}
{"level":"info","port":"9000","ip":"3.19.234.243","maxFirstID":0,"maxCount":17,"caller":"/data/harmony-main/api/service/syncing/syncing.go:323","time":"2019-09-12T22:02:17.161054085Z","message":"[SYNC] block consensus hashes"}
{"level":"info","port":"9000","ip":"3.19.234.243","caller":"/data/harmony-main/api/service/syncing/syncing.go:371","time":"2019-09-12T22:02:17.165927652Z","message":"[SYNC] Finished getting consensus block hashes"}
{"level":"info","port":"9000","ip":"3.19.234.243","length":103,"caller":"/data/harmony-main/api/service/syncing/syncing.go:390","time":"2019-09-12T22:02:17.165960738Z","message":"[SYNC] Finished generateStateSyncTaskQueue"}
{"level":"info","port":"9000","ip":"3.19.234.243","caller":"/data/harmony-main/api/service/syncing/syncing.go:454","time":"2019-09-12T22:02:17.262647146Z","message":"[SYNC] Finished downloadBlocks"}
{"level":"info","port":"9000","ip":"3.19.234.243","blockHex":"0xd4260bc6b2ddaf44e35cd31ddb752618bcdb093ddd8966eb24041c34987ac89e","caller":"/data/harmony-main/api/service/syncing/syncing.go:538","time":"2019-09-12T22:02:17.26276275Z","message":"[SYNC] Current Block"}
{"level":"info","port":"9000","ip":"3.19.234.243","epoch":1,"caller":"/data/harmony-main/core/resharding.go:227","time":"2019-09-12T22:02:17.26278354Z","message":"Get Shard State of Epoch."}
{"level":"info","port":"9000","ip":"3.19.234.243","epoch":1,"caller":"/data/harmony-main/core/resharding.go:227","time":"2019-09-12T22:02:17.658409095Z","message":"Get Shard State of Epoch."}
{"level":"info","port":"9000","ip":"3.19.234.243","epoch":1,"caller":"/data/harmony-main/core/resharding.go:227","time":"2019-09-12T22:02:17.966570395Z","message":"Get Shard State of Epoch."}
{"level":"info","port":"9000","ip":"3.19.234.243","epoch":1,"caller":"/data/harmony-main/core/resharding.go:227","time":"2019-09-12T22:02:18.351407153Z","message":"Get Shard State of Epoch."}
{"level":"info","port":"9000","ip":"3.19.234.243","epoch":1,"caller":"/data/harmony-main/core/resharding.go:227","time":"2019-09-12T22:02:18.66530892Z","message":"Get Shard State of Epoch."}
{"level":"info","port":"9000","ip":"3.19.234.243","caller":"/data/harmony-main/api/service/networkinfo/service.go:226","time":"2019-09-12T22:02:18.777111725Z","message":"PeerInfo Channel Closed"}{"level":"info","port":"9000","ip":"3.19.234.243","epoch":1,"caller":"/data/harmony-main/core/resharding.go:227","time":"2019-09-12T22:02:19.06450833Z","message":"Get Shard State of Epoch."}
{"level":"info","port":"9000","ip":"3.19.234.243","epoch":1,"caller":"/data/harmony-main/core/resharding.go:227","time":"2019-09-12T22:02:19.397208607Z","message":"Get Shard State of Epoch."}
{"level":"debug","port":"9000","ip":"3.19.234.243","caller":"/data/harmony-main/consensus/consensus_v2.go:428","time":"2019-09-12T22:02:19.657114375Z","message":"[OnPrepared] Received Prepared message"}
{"level":"info","port":"9000","ip":"3.19.234.243","MsgBlockNum":4082,"MsgViewID":4082,"caller":"/data/harmony-main/consensus/consensus_v2.go:455","time":"2019-09-12T22:02:19.662516386Z","message":"[OnPrepared] Received prepared message"}
{"level":"debug","port":"9000","ip":"3.19.234.243","MsgViewID":4082,"MsgBlockNum":4082,"blockHash":"dd4e4ae4ce7f9ec05b71d717643a26b8d763138f7058e2da96953a891429b2c9","caller":"/data/harmony-main/consensus/consensus_v2.go:536","time":"2019-09-12T22:02:19.671581035Z","message":"[OnPrepared] Prepared message and block added"}
{"level":"info","port":"9000","ip":"3.19.234.243","caller":"/data/harmony-main/consensus/consensus_v2.go:942","time":"2019-09-12T22:02:19.671598472Z","message":"[TryCatchup] commit new blocks"}
{"level":"info","port":"9000","ip":"3.19.234.243","caller":"/data/harmony-main/consensus/consensus_v2.go:957","time":"2019-09-12T22:02:19.671665251Z","message":"[TryCatchup] committed message found"}
{"level":"info","port":"9000","ip":"3.19.234.243","epoch":1,"caller":"/data/harmony-main/core/resharding.go:227","time":"2019-09-12T22:02:19.672390075Z","message":"Get Shard State of Epoch."}
{"level":"info","port":"9000","ip":"3.19.234.243","epoch":1,"caller":"/data/harmony-main/core/resharding.go:227","time":"2019-09-12T22:02:19.915524855Z","message":"Get Shard State of Epoch."}
{"level":"error","port":"9000","ip":"3.19.234.243","caller":"/data/harmony-main/core/blockchain.go:1663","time":"2019-09-12T22:02:20.356390082Z","message":"\n########## BAD BLOCK #########\nChain config: {ChainID: 2 EIP155: 0 CrossTx: 1 CrossLink: 2}\n\nNumber: 3975\nHash: 0x145032a1f8dadeac70241f7c9bcd0f8a1ca6fb8c12d6a6f34ee11c8e5d56d2e9\n\n\nError: unknown ancestor\n##############################\n"}
{"level":"error","port":"9000","ip":"3.19.234.243","error":"unknown ancestor","caller":"/data/harmony-main/api/service/syncing/syncing.go:552","time":"2019-09-12T22:02:20.35643855Z","message":"[SYNC] Error adding new block to blockchain 3979 3"}
{"level":"debug","port":"9000","ip":"3.19.234.243","block":{"ReceivedAt":"0001-01-01T00:00:00Z","ReceivedFrom":null},"caller":"/data/harmony-main/api/service/syncing/syncing.go:554","time":"2019-09-12T22:02:20.356460824Z","message":"[SYNC] Rolling back current block!"}
```

**Comment by xChickens** [comment]
2019/09/12 22:02:20 Stderr: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa36d62]

goroutine 101 [running]:
github.com/harmony-one/harmony/block.(*Header).EncodeRLP(0x0, 0x147bc80, 0xc015d46000, 0x7ff2b4cf21d8, 0x0)
        /data/harmony-main/block/header.go:27 +0x22
github.com/ethereum/go-ethereum/rlp.writeEncoder(0x1104a40, 0x0, 0x16, 0xc015d46000, 0x0, 0x0)
        /data/go-libs/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/rlp/encode.go:472 +0x97
github.com/ethereum/go-ethereum/rlp.(*encbuf).encode(0xc015d46000, 0x1104a40, 0x0, 0x107b020, 0xc015d46000)
        /data/go-libs/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/rlp/encode.go:187 +0x135
github.com/ethereum/go-ethereum/rlp.Encode(0x7ff2b4cf05d8, 0xc0163696c0, 0x1104a40, 0x0, 0x0, 0x0)
        /data/go-libs/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/rlp/encode.go:89 +0xf6
github.com/harmony-one/harmony/crypto/hash.FromRLP(0x1104a40, 0x0, 0x9716003dfa5d083d, 0xc048e973cc8af942, 0x28701e43da74509d, 0x86f860e7e301b9a)
        /data/harmony-main/crypto/hash/rlp.go:12 +0xc0
github.com/harmony-one/harmony/block.(*Header).Hash(...)
        /data/harmony-main/block/header.go:49
github.com/harmony-one/harmony/core.(*HeaderChain).SetCurrentHeader(0xc000414240, 0x0)
        /data/harmony-main/core/headerchain.go:450 +0x4c
github.com/harmony-one/harmony/core.(*BlockChain).Rollback(0xc0004b0000, 0xc0173c7bc0, 0x1, 0x1)
        /data/harmony-main/core/blockchain.go:837 +0x77e
github.com/harmony-one/harmony/api/service/syncing.(*StateSync).updateBlockAndStatus(0xc001e2fe30, 0xc015740a00, 0xc0004b0000, 0xc0009e2820, 0x9ec87a98341c0424)
        /data/harmony-main/api/service/syncing/syncing.go:555 +0x494
github.com/harmony-one/harmony/api/service/syncing.(*StateSync).generateNewState(0xc001e2fe30, 0xc0004b0000, 0xc0009e2820)
        /data/harmony-main/api/service/syncing/syncing.go:579 +0x12c
github.com/harmony-one/harmony/api/service/syncing.(*StateSync).ProcessStateSync(0xc001e2fe30, 0xc013f93480, 0x20, 0x20, 0x9ec87a9800000066, 0xc0004b0000, 0xc0009e2820)
        /data/harmony-main/api/service/syncing/syncing.go:639 +0xb0
github.com/harmony-one/harmony/api/service/syncing.(*StateSync).SyncLoop(0xc001e2fe30, 0xc0004b0000, 0xc0009e2820, 0x1)
        /data/harmony-main/api/service/syncing/syncing.go:760 +0xdf
github.com/harmony-one/harmony/node.(*Node).DoSyncing(0xc000123000, 0xc0004b0000, 0xc0009e2820, 0x1)
        /data/harmony-main/node/node_syncing.go:229 +0x1a4
created by github.com/harmony-one/harmony/node.(*Node).SupportSyncing
        /data/harmony-main/node/node_syncing.go:262 +0xa5
2019/09/12 22:02:20 Command finished with error: exit status 2
