### ISSUE TITLE
harmony node crash

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1607]
**Describe the bug**

A crash on harmony node. The following is from the log.

```
{"level":"info","port":"9000","ip":"52.32.215.173","publicKey":"0e790e10f49717e99be4fabf6ec497692557c81b6f932344e2877a7d1fe552874d7c79d99c366e25ddee27647e56ad94","caller":"/mnt/jenkins/workspace/harmony-release/harmony/consensus/consensus.go:276","time":"2019-09-17T18:36:44.261639491Z","message":"My Public Key"}
{"level":"warn","port":"9000","ip":"52.32.215.173","hash":"0xbed7d0fe3c9d4e6a3147d3a01e2f44b2f9837b142c1cc07016fa92466a8458bc","caller":"/mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:284","time":"2019-09-17T18:36:44.408509314Z","message":"Head block missing, resetting chain"}
{"level":"warn","port":"9000","ip":"52.32.215.173","target":0,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:352","time":"2019-09-17T18:36:44.408535082Z","message":"Rewinding blockchain"}
```

```
Sep 17 10:52:44 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: node.sh: ############### Running Harmony Process ###############
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: My Genesis Account: one1896gz9wxlne9vnea4pllfheyn3m3a3mq7z7jkp/0e790e10f49717e99be4fabf6ec497692557c81b6f932344e
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: panic: interface conversion: interface {} is nil, not *types.Block
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: goroutine 1 [running]:
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: github.com/harmony-one/harmony/core.(*BlockChain).CurrentBlock(...)
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: /mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:439
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: github.com/harmony-one/harmony/core.(*BlockChain).SetHead(0xc000e6a000, 0x0, 0x0, 0x0)
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: /mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:373 +0xbe9
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: github.com/harmony-one/harmony/core.(*BlockChain).ResetWithGenesisBlock(0xc000e6a000, 0xc0000c4280, 0x0, 0x0)
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: /mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:495 +0x43
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: github.com/harmony-one/harmony/core.(*BlockChain).Reset(0xc000e6a000, 0x112e1d3, 0x23)
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: /mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:488 +0x37
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: github.com/harmony-one/harmony/core.(*BlockChain).loadLastState(0xc000e6a000, 0x0, 0xc0000c4280)
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: /mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:285 +0x1516
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: github.com/harmony-one/harmony/core.NewBlockChain(0x1498300, 0xc0003e2160, 0xc00063cae0, 0xc000097bf0, 0x149e000
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: /mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:205 +0x67c
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: github.com/harmony-one/harmony/internal/shardchain.(*CollectionImpl).ShardChain(0xc0003d2230, 0xc000000000, 0x0,
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: /mnt/jenkins/workspace/harmony-release/harmony/internal/shardchain/shardchains.go:97 +0x3d0
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: github.com/harmony-one/harmony/node.(*Node).Blockchain(0xc0001ba000, 0xc0003d2230)
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: /mnt/jenkins/workspace/harmony-release/harmony/node/node.go:223 +0x5b
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: github.com/harmony-one/harmony/node.New(0x149e060, 0xc0000a2510, 0xc000138000, 0x1475ec0, 0xc00003c110, 0x1, 0x0
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: /mnt/jenkins/workspace/harmony-release/harmony/node/node.go:386 +0x355
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: main.setupConsensusAndNode(0xc000420000, 0x7)
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: /mnt/jenkins/workspace/harmony-release/harmony/cmd/harmony/main.go:301 +0x35f
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: main.main()
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: /mnt/jenkins/workspace/harmony-release/harmony/cmd/harmony/main.go:449 +0x50b
Sep 17 10:52:47 ip-172-31-0-214.us-west-2.compute.internal node.sh[411]: node.sh: node process finished with status 2

```

**Comment by LeoHChen** [comment]
[ec2-user@ip-172-31-0-214 ~]$ LD_LIBRARY_PATH=. ./harmony -version
Harmony (C) 2019. harmony, version v4560-v1-20190911.1-0-gaafdaa47 (jenkins@ 2019-09-11T21:32:15+0000)

**Comment by rlan35** [comment]
https://github.com/harmony-one/harmony/blame/master/core/blockchain.go#L439 The crash happened here, because the currentBlock.Load() is nil. It's basically a data corruption issue.

**Comment by LeoHChen** [comment]
after discussion with @rlan35 , this is possible db corruption due to the out of space we had recently.  The crash is the right thing to do right now.

**Comment by LeoHChen** [comment]
I'll try to recover the node using the pre-sync'ed harmony_db.

**Comment by AndyBoWu** [comment]
@LeoHChen @rlan35 I have seen the similar symptoms in this node `52.53.216.192`.

**Comment by LeoHChen** [comment]
52.53.216.192 is recovered already.  I am using db snapshot to recover 52.32.215.173.

**Comment by LeoHChen** [comment]
52.32.215.173 is recovered.
