### ISSUE TITLE
panic from p2p

### ISSUE THREAD

**Issue by fxfactorial** [harmony-one/harmony#1729]
running latest cut of master, 9f00923ac344d297f5347958f38b909e1656e95a, and getting this panic after `test/debug.sh`

```
panic: catchError

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1(0x4d299b8, 0xa)
	/Users/edgar/Repos/harmony-work/pkg/mod/github.com/rs/zerolog@v1.14.3/log.go:319 +0x4f
github.com/rs/zerolog.(*Event).msg(0xc0000de8a0, 0x4d299b8, 0xa)
	/Users/edgar/Repos/harmony-work/pkg/mod/github.com/rs/zerolog@v1.14.3/event.go:141 +0x1c1
github.com/rs/zerolog.(*Event).Msg(...)
	/Users/edgar/Repos/harmony-work/pkg/mod/github.com/rs/zerolog@v1.14.3/event.go:105
github.com/harmony-one/harmony/p2p/host/hostv2.catchError(0x508f140, 0xc0000e28b0)
	/Users/edgar/Repos/harmony-work/src/github.com/harmony-one/harmony/p2p/host/hostv2/util.go:7 +0x86
github.com/harmony-one/harmony/p2p/host/hostv2.New(0xc0003b5d18, 0x50b25c0, 0xc0000d8ea0, 0x4a67101)
	/Users/edgar/Repos/harmony-work/src/github.com/harmony-one/harmony/p2p/host/hostv2/hostv2.go:172 +0x362
github.com/harmony-one/harmony/p2p/p2pimpl.NewHost(0xc0003b5d18, 0x50b25c0, 0xc0000d8ea0, 0xc0000d8ea0, 0x50ae400, 0xc0001faab0, 0x0)
	/Users/edgar/Repos/harmony-work/src/github.com/harmony-one/harmony/p2p/p2pimpl/p2pimpl.go:17 +0x5a
main.createGlobalConfig(0x4d71501)
	/Users/edgar/Repos/harmony-work/src/github.com/harmony-one/harmony/cmd/harmony/main.go:276 +0x243
main.main()
	/Users/edgar/Repos/harmony-work/src/github.com/harmony-one/harmony/cmd/harmony/main.go:474 +0x551
```

@LeoHChen I think maybe something with p2p related code?

**Comment by LeoHChen** [comment]
I believe this one has been fixed.
