### ISSUE TITLE
blockchain crashes after sending a validator creation txn

### ISSUE THREAD

**Issue by mikedoan** [harmony-one/harmony#1880]
```
waiting for the result
====== WALLET BALANCES ======
Using local profile for wallet
Account: one1spshr72utf6rwxseaz339j09ed8p6f8ke370zj:
    Balance in Shard 0:  141.142647142, nonce: 10
    Balance in Shard 1:  0.0000, nonce: 0
Using local profile for wallet
Account: one1uyshu2jgv8w465yc8kkny36thlt2wvel89tcmg:
    Balance in Shard 0:  0.0000, nonce: 0
    Balance in Shard 1:  69.475980476, nonce: 10
Using local profile for wallet
Account: one1r4zyyjqrulf935a479sgqlpa78kz7zlcg2jfen:
    Balance in Shard 0:  1.0000, nonce: 0
    Balance in Shard 1:  1.0000, nonce: 0
====== RESULTS ======
PASS
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x410ab18]

goroutine 357 [running]:
math/big.(*Int).Add(0xc001372dc0, 0xc001372d20, 0x0, 0xc00b0bc600)
	/usr/local/go/src/math/big/int.go:118 +0x38
github.com/harmony-one/harmony/numeric.Dec.Add(0xc001372d20, 0x0, 0xc001e2a858)
	/Users/minhdoan/go/src/github.com/harmony-one/harmony/numeric/decimal.go:217 +0x53
github.com/harmony-one/harmony/consensus/quorum.(*stakedVoteWeight).computeCurrentTotalPower(0xc009433570, 0x400000c001e2a800, 0x6)
	/Users/minhdoan/go/src/github.com/harmony-one/harmony/consensus/quorum/one-node-staked-vote.go:80 +0x1f5
github.com/harmony-one/harmony/consensus/quorum.(*stakedVoteWeight).IsQuorumAchieved(0xc009433570, 0xc00a300200, 0xc00a300201)
	/Users/minhdoan/go/src/github.com/harmony-one/harmony/consensus/quorum/one-node-staked-vote.go:61 +0x4b
github.com/harmony-one/harmony/consensus.(*Consensus).onPrepare(0xc00051b180, 0xc0011e46e0)
	/Users/minhdoan/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:398 +0xdcf
github.com/harmony-one/harmony/consensus.(*Consensus).handleMessageUpdate(0xc00051b180, 0xc00b4d6506, 0x121, 0x13a)
	/Users/minhdoan/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:73 +0x177
github.com/harmony-one/harmony/consensus.(*Consensus).Start.func1(0xc00051b180, 0xc000524000, 0xc000330660, 0xc000572c60, 0xc000330600)
	/Users/minhdoan/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:1233 +0xaf7
created by github.com/harmony-one/harmony/consensus.(*Consensus).Start
	/Users/minhdoan/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:1073 +0x67
```

**Comment by rlan35** [comment]
Please retry with the latest master code.
