### ISSUE TITLE
Div by 0 when creating validator

### ISSUE THREAD

**Issue by Daniel-VDM** [harmony-one/harmony#2167]
**Describe the bug**
On localnet, I created a validator using the CLI with the following command.
```
hmy --node=http://127.0.0.1:9500 staking create-validator --validator-addr one1acxxp4wef0vegng27evh0qkffakq5m40gsc2r7 --name _Test_key_validator0 --identity test_account --website harmony.one --security-contact Daniel-VDM --details none --rate 0.16798352018382678 --max-rate 0.1791844697821372 --max-change-rate 0.1522127615232536 --min-self-delegation 1 --max-total-delegation 6 --amount 3 --bls-pubkeys 3d036dedd8a73dde3f0d00bf6adaedd96267f8c0bc47aa156537a80eb733bf4a1575a84a07fd341144d7183d3cb2c686 --chain-id testnet
```

And I got the following stack trace:
```
panic: division by zero

goroutine 161 [running]:
math/big.nat.div(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/math/big/nat.go:648 +0x481
math/big.(*Int).QuoRem(0xc00919b738, 0xc00919b6b8, 0xc00919b698, 0xc00919b500, 0x0, 0x0)
    /usr/local/go/src/math/big/int.go:239 +0xbf
math/big.(*Int).Div(0xc00919b738, 0xc00919b6b8, 0xc00919b698, 0xc00919b698)
    /usr/local/go/src/math/big/int.go:250 +0x6d
github.com/harmony-one/harmony/staking/availability.SetInactiveUnavailableValidators(0x515edc0, 0xc0001c2000, 0xc0001fd5f0, 0xc00919bac8, 0xc0001fd5f0, 0xc00919bac8)
    /Users/danielvdm/go/src/github.com/harmony-one/harmony/staking/availability/measure.go:201 +0x457
github.com/harmony-one/harmony/node.(*Node).proposeNewBlock(0xc00029a380, 0x4e105d8, 0x44, 0x32)
    /Users/danielvdm/go/src/github.com/harmony-one/harmony/node/node_newblock.go:204 +0xc7c
github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyV2.func1(0xc006250c00, 0xc00029a380, 0xc006250ba0, 0xc00020aea0)
    /Users/danielvdm/go/src/github.com/harmony-one/harmony/node/node_newblock.go:56 +0x22a
created by github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyV2
    /Users/danielvdm/go/src/github.com/harmony-one/harmony/node/node_newblock.go:27 +0x5d
```
I was not running a node when I tried to create the validator. 

**To Reproduce**
1. Checkout commit `9fe8792c022b650476da4e3ae2fb90f28aa2170a`
2. Run localnet
3. Wait for staking epoch
4. Create a validator via CLI without running a node

**Expected behavior**
No panic

**Comment by rlan35** [comment]
@fxfactorial fixed?

**Comment by fxfactorial** [comment]
@rlan35 fixed in https://github.com/harmony-one/harmony/pull/2185
