### ISSUE TITLE
hmy export-ks & export-private-key fails

### ISSUE THREAD

**Issue by gaia** [harmony-one/harmony#2252]
**Environment (please complete the following information):**
- OS: Ubuntu 18.04.4 (native on bare-metal)

```
$ ./hmy version
Harmony (C) 2020. hmy, version v267-0d819bd (edgar@harmony.one 2020-02-11T16:59:15-0800)

$ ./hmy keys list
NAME                                                    ADDRESS

main                                                    one1____________________

$ ./hmy keys export-private-key main
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9b8fee]

goroutine 1 [running]:
github.com/harmony-one/harmony/accounts/keystore.(*KeyStore).Accounts(...)
        /home/edgar/go/pkg/mod/github.com/harmony-one/harmony@v1.3.0/accounts/keystore/keystore.go:232
github.com/harmony-one/go-sdk/pkg/account.ExportPrivateKey(0x7ffc81470753, 0x4, 0x0, 0x0, 0x0, 0x0)
        /home/edgar/go/src/github.com/harmony-one/go-sdk/pkg/account/export.go:12 +0x5e
github.com/harmony-one/go-sdk/cmd/subcommands.keysSub.func8(0xc0002fb900, 0xc00028b0b0, 0x1, 0x1, 0x0, 0x0)
        /home/edgar/go/src/github.com/harmony-one/go-sdk/cmd/subcommands/keys.go:213 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc0002fb900, 0xc00028b080, 0x1, 0x1, 0xc0002fb900, 0xc00028b080)
        /home/edgar/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x1531e40, 0x1, 0xffffffffffffffff, 0x7)
        /home/edgar/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/edgar/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/harmony-one/go-sdk/cmd/subcommands.Execute()
        /home/edgar/go/src/github.com/harmony-one/go-sdk/cmd/subcommands/root.go:112 +0x4d
main.main()
        /home/edgar/go/src/github.com/harmony-one/go-sdk/cmd/main.go:38 +0x163

$ ./hmy keys export-ks main
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9b92ae]

goroutine 1 [running]:
github.com/harmony-one/harmony/accounts/keystore.(*KeyStore).Accounts(...)
        /home/edgar/go/pkg/mod/github.com/harmony-one/harmony@v1.3.0/accounts/keystore/keystore.go:232
github.com/harmony-one/go-sdk/pkg/account.ExportKeystore(0x7ffcf906d753, 0x4, 0x0, 0x0, 0x0, 0x0)
        /home/edgar/go/src/github.com/harmony-one/go-sdk/pkg/account/export.go:25 +0x5e
github.com/harmony-one/go-sdk/cmd/subcommands.keysSub.func9(0xc000333900, 0xc000314950, 0x1, 0x1, 0x0, 0x0)
        /home/edgar/go/src/github.com/harmony-one/go-sdk/cmd/subcommands/keys.go:228 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc000333900, 0xc000314920, 0x1, 0x1, 0xc000333900, 0xc000314920)
        /home/edgar/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x1531e40, 0x1, 0xffffffffffffffff, 0x7)
        /home/edgar/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/edgar/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/harmony-one/go-sdk/cmd/subcommands.Execute()
        /home/edgar/go/src/github.com/harmony-one/go-sdk/cmd/subcommands/root.go:112 +0x4d
main.main()
        /home/edgar/go/src/github.com/harmony-one/go-sdk/cmd/main.go:38 +0x163
```

**Comment by Cem-Harmony** [comment]
Reproduced by building new Docker image using main repo Dockerfile
* Host OS: macOS 10.14.6
* Docker Desktop: 2.2.0.0 (42247)
* Ubuntu: 18.04.4 LTS
[Log as Gist](https://gist.github.com/Cem-Harmony/8fb908990450ea1f563951025b92f558)

Reproduced by building new Harmony CLI and running with shell script
* OS: macOS 10.14.6
[Log as Gist](https://gist.github.com/Cem-Harmony/1f98ef414a331b992d33384bd0ac28cd)

**Comment by janet-harmony** [comment]
Fixed on go-sdk.
