### ISSUE TITLE
organize all the logs 

### ISSUE THREAD

**Issue by fxfactorial** [harmony-one/harmony#2352]
currently our logging is ad-hoc and many things that are not errors are logged as errors. 

Plus the logging is incredibly verbose in code because lots of code does `utils.Logger().Info()...` and some variation of that. 

plus the hooking onto a global value is icky and causing issues like this: 
```
[ec2-user@ip-172-31-84-221 ~]$ cat soldier-3.84.77.235.log 
2020/03/02 14:59:36 HTTP server listen on port: 19000
2020/03/02 14:59:36 Supported API:
2020/03/02 14:59:36 /ping			I'm alive!
2020/03/02 14:59:36 /init			Start Benchmark/Txgen
2020/03/02 15:02:36 Init Handler
2020/03/02 15:02:36 running instance
2020/03/02 15:02:36 Command running ./harmony [-ip 3.84.77.235 -port 9000 -log_folder ../tmp_log/log-20200302.145828 -bootnodes /ip4/52.40.84.2/tcp/9876/p2p/QmbPVwrqWsTYXq1RxGWcxx9SWaTUCfoo1wA6wmdbduWe29 -min_peers 6 -blspass file:blsnopass.txt -blskey_file 021926136495a0adcdda5af0602cb4b4ce6d6529cfd451b844728a0e4e424f2a78879a8b5d5e4b3e42127f95f2e2858b.key -delay_commit=2s -network_type=testnet -dns_zone=ds.hmny.io -public_rpc]
2020/03/02 16:11:16 Stderr: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x62e4d4]

goroutine 236 [running]:
github.com/rs/zerolog.(*Event).msg(0xc0069d2c00, 0x124407b, 0x1b)
	/home/ec2-user/go/pkg/mod/github.com/rs/zerolog@v1.14.3/event.go:123 +0xd4
github.com/rs/zerolog.(*Event).Msg(...)
	/home/ec2-user/go/pkg/mod/github.com/rs/zerolog@v1.14.3/event.go:105
github.com/harmony-one/harmony/node.(*Node).PostConsensusProcessing(0xc000118e00, 0xc000233a40, 0xc000e7c7e0, 0x61, 0x61)
	/home/ec2-user/edgar/harmony/node/node_handler.go:439 +0xb0d
github.com/harmony-one/harmony/consensus.(*Consensus).tryCatchup(0xc0000c7180)
	/home/ec2-user/edgar/harmony/consensus/consensus_v2.go:272 +0x4d6
github.com/harmony-one/harmony/consensus.(*Consensus).onCommitted(0xc0000c7180, 0xc0078f7e00)
	/home/ec2-user/edgar/harmony/consensus/validator.go:286 +0x582
github.com/harmony-one/harmony/consensus.(*Consensus).handleMessageUpdate(0xc0000c7180, 0xc006bf8c86, 0x126, 0x13a)
	/home/ec2-user/edgar/harmony/consensus/consensus_v2.go:90 +0x2f8
github.com/harmony-one/harmony/consensus.(*Consensus).Start.func1(0xc0000c7180, 0xc0002fe8a0, 0xc000e40600, 0xc0000857a0, 0xc000e405a0)
	/home/ec2-user/edgar/harmony/consensus/consensus_v2.go:471 +0x615
created by github.com/harmony-one/harmony/consensus.(*Consensus).Start
	/home/ec2-user/edgar/harmony/consensus/consensus_v2.go:308 +0x67
2020/03/02 16:11:16 Command finished with error: exit status 2
[ec2-user@ip-172-31-84-221 ~]$ 

```

so we need to have major components be have their own namespaced loggers, like consensus sort of does.

**Comment by fxfactorial** [comment]
No one care
