### ISSUE TITLE
STN/stressnet: Consensus lost on shard 0 after double-sign tests

### ISSUE THREAD

**Issue by SebastianJ** [harmony-one/harmony#2625]
**Describe the bug**
I ran the exact same set of tests that resulted in issue #2615 - with the difference that STN was relaunched using https://github.com/harmony-one/harmony/pull/2623

Now nodes seem to crash/panic:

```
panic: division by zero

goroutine 228 [running]:
math/big.nat.div(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/math/big/nat.go:648 +0x481
math/big.(*Int).Quo(0xc00c6d3cc0, 0xc006c1a750, 0xc00c6d3c80, 0xc006c1a750)
        /usr/local/go/src/math/big/int.go:212 +0xad
github.com/harmony-one/harmony/numeric.Dec.Quo(0xc00c6d3ca0, 0xc00c6d3c80, 0xc00c6d3ca0)
        /home/ec2-user/JL/harmony/numeric/decimal.go:284 +0xb1
github.com/harmony-one/harmony/core/state.(*DB).AddReward(0xc00da7e9c0, 0xc006c12a00, 0xc00c6d35a0, 0xc00c73c0c0, 0xc006c12a00)
        /home/ec2-user/JL/harmony/core/state/statedb.go:768 +0x452
github.com/harmony-one/harmony/internal/chain.AccumulateRewards(0x15ebdc0, 0xc000198000, 0xc00da7e9c0, 0xc00ccdec40, 0x15ebdc0, 0xc000198000, 0x0, 0x0, 0xc006c1b4c8, 0x412f86)
        /home/ec2-user/JL/harmony/internal/chain/reward.go:295 +0x19a3
github.com/harmony-one/harmony/internal/chain.(*engineImpl).Finalize(0x218d1b0, 0x15ebdc0, 0xc000198000, 0xc00ccdec40, 0xc00da7e9c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ec2-user/JL/harmony/internal/chain/engine.go:262 +0x83
github.com/harmony-one/harmony/node/worker.(*Worker).FinalizeNewBlock(0xc0000ce500, 0xc00020a660, 0x60, 0x60, 0xc009761048, 0x4, 0x4, 0x19d5, 0x546f45c50e686e3f, 0xd28e4cdf773e830a, ...)
        /home/ec2-user/JL/harmony/node/worker/worker.go:458 +0x68e
github.com/harmony-one/harmony/node.(*Node).proposeNewBlock(0xc0002cb500, 0x0, 0x0, 0x0)
        /home/ec2-user/JL/harmony/node/node_newblock.go:239 +0xeb4
github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyV2.func1(0xc000097e60, 0xc0002cb500, 0xc000097e00, 0xc0004a61e0)
        /home/ec2-user/JL/harmony/node/node_newblock.go:59 +0x269
created by github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyV2
        /home/ec2-user/JL/harmony/node/node_newblock.go:27 +0x5d
```

**To Reproduce**
```
bash <(curl -sSL https://raw.githubusercontent.com/SebastianJ/harmony-tools/master/double-signing/setup.sh) --network stress --shard 1 --address ADDRESS_WITH_FUNDS
```

**Expected behavior**
Shard 0 should be able to deal with double-signing validators.

**Comment by fxfactorial** [comment]
Should be fixed by https://github.com/harmony-one/harmony/pull/2626

**Comment by lijiang2087** [comment]
should we close this one then? @fxfactorial

**Comment by fxfactorial** [comment]
convention on closing issues is that OP will try again same initial conditions after mentioned PR is merged/deployed.

**Comment by SebastianJ** [comment]
Tested on STN with latest master, managed to get 100% slashed validators + delegators and nodes still haven't crashed due to `division by zero` - so seems to be fixed
