### ISSUE TITLE
beacon node segfault

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#276]
**Describe the bug**
Got an invalid memory address issue on running bin/beacon.

$ bin/beacon
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xa1f1bd]

goroutine 1 [running]:
github.com/harmony-one/harmony/internal/beaconchain/libs.(*BeaconChain).GetID(0xc420001e00, 0xe, 0xc420001e00)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/internal/beaconchain/libs/beaconchain.go:199 +0x2d
main.main()
        /home/ec2-user/go/src/github.com/harmony-one/harmony/cmd/beaconchain/main.go:52 +0x301

**To Reproduce**
1. Check out code with latest commit
2. Build
3. run local test using "bin/beacon" commands
4. start a harmony node to register with beacon chain
5. control-c to terminate beacon chain
6. run "bin/beacon" command again.

**Expected behavior**
beacon command shouldn't get segfault.  

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by LeoHChen** [comment]
beacon node is no longer needed.
