### ISSUE TITLE
OOB + possible binary version not updating

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2973]
**Describe the bug**

the OOB issue reappeared today. And while we did some investigation, the conclusion is we cant download any newer version than Harmony (C) 2019. harmony, version v5084-v1.2.5-1-g80ea0ce9 (jenkins@ 2020-04-02T22:14:23+0000), which does not seem to have the OOB fix. I tried deleting all files and redownloaded node.sh, but the binary that it pulls down is the same.

stack trace for OOB:
May 10 00:35:43 harmony1 harmonyd[11189]: INFO: found UTC--2019-06-13T20-47-04.290471729Z--bls_fce3097d9fc234d34d6eaef3eecd0
May 10 00:35:43 harmony1 harmonyd[11189]: INFO: public IP address autodetected: 34.94.7.216
May 10 00:36:25 harmony1 harmonyd[11189]: panic: runtime error: slice bounds out of range [5:0]
May 10 00:36:25 harmony1 harmonyd[11189]:
May 10 00:36:25 harmony1 harmonyd[11189]: goroutine 1942 [running]:
May 10 00:36:25 harmony1 harmonyd[11189]: github.com/harmony-one/harmony/node.(Node).receiveGroupMessage(0xc000188800, 0x14
May 10 00:36:25 harmony1 systemd[1]: harmony.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 10 00:36:25 harmony1 harmonyd[11189]:         /mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:59 +0x
May 10 00:36:25 harmony1 harmonyd[11189]: created by github.com/harmony-one/harmony/node.(Node).startRxPipeline
May 10 00:36:25 harmony1 systemd[1]: harmony.service: Failed with result 'exit-code'.
May 10 00:36:25 harmony1 harmonyd[11189]:         /mnt/jenkins/workspace/harmony-release/harmony/node/node.go:417 +0xc0
May 10 00:36:25 harmony1 systemd[1]: harmony.service: Service hold-off time over, scheduling restart.
May 10 00:36:25 harmony1 systemd[1]: harmony.service: Scheduled restart job, restart counter is at 4.

due to the abuse emails some of us are getting from service providers, i would also ask if we can implement #2940

**Comment by mindstyle85** [comment]
OOB should be patched with the latest upgrade, closing for now
