### ISSUE TITLE
[panic] nil pointer returned by GetHeaderByNumber, GetHeader wasn't checked

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3022]
When I was handling the out of sync ticket, found the following panic

```
	May 15 13:07:19 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: 2020/05/15 13:07:19 http: Accept error: accept tcp [::]:9500: accept4: too many open files;
May 15 13:07:19 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: 2020/05/15 13:07:19 http: Accept error: accept tcp [::]:9500: accept4: too many open files;
May 15 13:07:19 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: 2020/05/15 13:07:19 http: Accept error: accept tcp [::]:9500: accept4: too many open files;
May 15 13:07:20 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: 2020/05/15 13:07:20 http: Accept error: accept tcp [::]:9500: accept4: too many open files;
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: panic: runtime error: invalid memory address or nil pointer dereference
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb26415]
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: goroutine 937 [running]:
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: github.com/harmony-one/harmony/core.(*BlockChain).WriteBlockWithState(0xc000bf6000, 0xc00f8d
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: /mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:1140 +0x545
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: github.com/harmony-one/harmony/core.(*BlockChain).insertChain(0xc000bf6000, 0xc01f146f50, 0x
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: /mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:1387 +0x1257
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: github.com/harmony-one/harmony/core.(*BlockChain).InsertChain(0xc000bf6000, 0xc01f146f50, 0x
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: /mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:1205 +0x73
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: github.com/harmony-one/harmony/node.(*Node).PostConsensusProcessing(0xc0003dec80, 0xc00f8db2
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: /mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:401 +0x91
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: github.com/harmony-one/harmony/consensus.(*Consensus).tryCatchup(0xc0001fc900)
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: /mnt/jenkins/workspace/harmony-release/harmony/consensus/consensus_v2.go:300 +0x52d
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: github.com/harmony-one/harmony/consensus.(*Consensus).onCommitted(0xc0001fc900, 0xc01340dd10
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: /mnt/jenkins/workspace/harmony-release/harmony/consensus/validator.go:303 +0x55f
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: github.com/harmony-one/harmony/consensus.(*Consensus).handleMessageUpdate(0xc0001fc900, 0xc0
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: /mnt/jenkins/workspace/harmony-release/harmony/consensus/consensus_v2.go:79 +0x31e
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: github.com/harmony-one/harmony/consensus.(*Consensus).Start.func1(0xc0001fc900, 0xc000942480
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: /mnt/jenkins/workspace/harmony-release/harmony/consensus/consensus_v2.go:493 +0x616
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: created by github.com/harmony-one/harmony/consensus.(*Consensus).Start
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: /mnt/jenkins/workspace/harmony-release/harmony/consensus/consensus_v2.go:336 +0x67
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: node.sh: node process finished with status 2
May 15 13:08:06 ip-172-31-33-32.eu-west-1.compute.internal node.sh[25432]: node.sh: exiting
```

**Comment by LeoHChen** [comment]
![image](https://user-images.githubusercontent.com/4513927/82075156-ad968000-9690-11ea-81a2-98b23a195570.png)

**Comment by LeoHChen** [comment]
The GetHeaderByNumber may return nil pointer, so in all the code, we should check nil pointer on the return value of GetHeaderByNumber

**Comment by LeoHChen** [comment]
```
$ ag GetHeaderByNumber
consensus/engine/consensus_engine.go
31:     // GetHeaderByNumber retrieves a block header from the database by number.
32:     GetHeaderByNumber(number uint64) *block.Header

consensus/consensus_v2.go
527:    previousHeader := consensus.ChainReader.GetHeaderByNumber(
549:    previousHeader := consensus.ChainReader.GetHeaderByNumber(

core/blockchain.go
835:                            recent := bc.GetHeaderByNumber(number - offset)
1139:                   header := bc.GetHeaderByNumber(current - triesInMemory)
1682:// GetHeaderByNumber retrieves a block header from the database by number,
1684:func (bc *BlockChain) GetHeaderByNumber(number uint64) *block.Header {
1685:   return bc.hc.GetHeaderByNumber(number)
1776:   header := bc.GetHeaderByNumber(number)
1786:   header := bc.GetHeaderByNumber(number)
2130:   previousHeader := bc.GetHeaderByNumber(block.NumberU64() - 1)

core/chain_makers.go
259:func (cr *fakeChainReader) GetHeaderByNumber(number uint64) *block.Header           { return nil }

core/headerchain.go
97:     hc.genesisHeader = hc.GetHeaderByNumber(0)
432:// GetHeaderByNumber retrieves a block header from the database by number,
434:func (hc *HeaderChain) GetHeaderByNumber(number uint64) *block.Header {

node/node_cross_shard.go
102:            nextHeader := node.Blockchain().GetHeaderByNumber(blockNum + 1)

node/node_handler.go
259:            header := node.Blockchain().GetHeaderByNumber(newBlock.NumberU64() - 2)
263:            header = node.Blockchain().GetHeaderByNumber(newBlock.NumberU64() - 1)
271:                    header := node.Blockchain().GetHeaderByNumber(blockNum)

node/node_syncing.go
370:                    header := node.Blockchain().GetHeaderByNumber(blockNum)

node/node.go
509:            Interface("genesis block header", node.Blockchain().GetHeaderByNumber(0)).

hmy/api_backend.go
115:    return b.hmy.blockchain.GetHeaderByNumber(uint64(blockNr)), nil

staking/apr/compute.go
27:     GetHeaderByNumber(number uint64) *block.Header
106:    headerOneEpochAgo := bc.GetHeaderByNumber(blockNumAtOneEpochAgo)
```

**Comment by fxfactorial** [comment]
@rlan35 remember I hit this during APR impl, possible root cause problem is similar here ?

**Comment by LeoHChen** [comment]
```
May 16 19:28:56 ip-172-31-27-250.ap-southeast-1.compute.internal node.sh[9549]: 2020/05/16 19:28:56 http: Accept error: accept tcp [::]:9500: accept4: too many open fi
May 16 19:28:56 ip-172-31-27-250.ap-southeast-1.compute.internal node.sh[9549]: 2020/05/16 19:28:56 http: Accept error: accept tcp [::]:9500: accept4: too many open fi
May 16 19:37:33 ip-172-31-27-250.ap-southeast-1.compute.internal systemd[1]: Stopping harmony service...
May 16 19:37:33 ip-172-31-27-250.ap-southeast-1.compute.internal node.sh[9549]: Got terminated signal. Gracefully shutting down...
May 16 19:37:33 ip-172-31-27-250.ap-southeast-1.compute.internal node.sh[9549]: panic: runtime error: invalid memory address or nil pointer dereference
May 16 19:37:33 ip-172-31-27-250.ap-southeast-1.compute.internal node.sh[9549]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb226df]
May 16 19:37:33 ip-172-31-27-250.ap-southeast-1.compute.internal node.sh[9549]: goroutine 102 [running]:
May 16 19:37:33 ip-172-31-27-250.ap-southeast-1.compute.internal node.sh[9549]: github.com/harmony-one/harmony/core.(*BlockChain).Stop(0xc000470000)
May 16 19:37:33 ip-172-31-27-250.ap-southeast-1.compute.internal node.sh[9549]: /mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:838 +0x1ef
May 16 19:37:33 ip-172-31-27-250.ap-southeast-1.compute.internal node.sh[9549]: github.com/harmony-one/harmony/node.(*Node).ShutDown(0xc0003dcc80)
May 16 19:37:33 ip-172-31-27-250.ap-southeast-1.compute.internal node.sh[9549]: /mnt/jenkins/workspace/harmony-release/harmony/node/node.go:673 +0x3d
May 16 19:37:33 ip-172-31-27-250.ap-southeast-1.compute.internal node.sh[9549]: main.main.func1(0xc00114bb00, 0xc0003dcc80)
May 16 19:37:33 ip-172-31-27-250.ap-southeast-1.compute.internal node.sh[9549]: /mnt/jenkins/workspace/harmony-release/harmony/cmd/harmony/main.go:712 +0x1a1
May 16 19:37:33 ip-172-31-27-250.ap-southeast-1.compute.internal node.sh[9549]: created by main.main
May 16 19:37:33 ip-172-31-27-250.ap-southeast-1.compute.internal node.sh[9549]: /mnt/jenkins/workspace/harmony-release/harmony/cmd/harmony/main.go:706 +0x9ad
May 16 19:37:33 ip-172-31-27-250.ap-southeast-1.compute.internal node.sh[9549]: node.sh: received SIGTERM
May 16 19:37:33 ip-172-31-27-250.ap-southeast-1.compute.internal systemd[1]: Started harmony service.
```

**Comment by LeoHChen** [comment]
hit it again in another place during the rolling upgrade, @Daniel-VDM

**Comment by LeoHChen** [comment]
Hit another nil pointer panic on different function calls.

```
May 16 20:33:43 ip-172-31-54-91.us-west-2.compute.internal node.sh[20376]: panic: runtime error: invalid memory address or nil pointer dereference
May 16 20:33:43 ip-172-31-54-91.us-west-2.compute.internal node.sh[20376]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa97fb5]
May 16 20:33:43 ip-172-31-54-91.us-west-2.compute.internal node.sh[20376]: goroutine 744989 [running]:
May 16 20:33:43 ip-172-31-54-91.us-west-2.compute.internal node.sh[20376]: github.com/harmony-one/harmony/internal/chain.(*engineImpl).VerifySeal(0x2803a30, 0x1ad4620,
May 16 20:33:43 ip-172-31-54-91.us-west-2.compute.internal node.sh[20376]: /mnt/jenkins/workspace/harmony-release/harmony/internal/chain/engine.go:191 +0x405
May 16 20:33:43 ip-172-31-54-91.us-west-2.compute.internal node.sh[20376]: github.com/harmony-one/harmony/internal/chain.(*engineImpl).VerifyHeader(0x2803a30, 0x1ad462
May 16 20:33:43 ip-172-31-54-91.us-west-2.compute.internal node.sh[20376]: /mnt/jenkins/workspace/harmony-release/harmony/internal/chain/engine.go:95 +0x10b
May 16 20:33:43 ip-172-31-54-91.us-west-2.compute.internal node.sh[20376]: github.com/harmony-one/harmony/internal/chain.(*engineImpl).VerifyHeaders.func1(0xc019266700
May 16 20:33:43 ip-172-31-54-91.us-west-2.compute.internal node.sh[20376]: /mnt/jenkins/workspace/harmony-release/harmony/internal/chain/engine.go:110 +0x102
May 16 20:33:43 ip-172-31-54-91.us-west-2.compute.internal node.sh[20376]: created by github.com/harmony-one/harmony/internal/chain.(*engineImpl).VerifyHeaders
May 16 20:33:43 ip-172-31-54-91.us-west-2.compute.internal node.sh[20376]: /mnt/jenkins/workspace/harmony-release/harmony/internal/chain/engine.go:108 +0x107
May 16 20:33:43 ip-172-31-54-91.us-west-2.compute.internal node.sh[20376]: node.sh: node process finished with status 2
May 16 20:33:44 ip-172-31-54-91.us-west-2.compute.internal systemd[1]: harmony.service holdoff time over, scheduling restart.
```

**Comment by LeoHChen** [comment]
Did a quick check on core/headerchain.go file and found the GetHeaderByHash, GetHeaderByNumber, GetHeader functions all may return nil pointer, but in many places, the return values weren't checked.  That's why we hit many nil pointer crashes now.
