### ISSUE TITLE
concurrent map write error

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#305]
**Describe the bug**
There is a fatal error found during a nightly benchmark run.
We should use a mutex to protect concurrent writes on the map variable.

**To Reproduce**

run nightly benchmark test 

**Expected behavior**
harmony node software shouldn't crash

**Screenshots/Logs**
```
2019/01/23 14:04:20 Stderr fatal error: concurrent map writes

goroutine 2482 [running]:
runtime.throw(0xdaadd5, 0x15)
   /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc001a75c80 sp=0xc001a75c50 pc=0x42e732
runtime.mapassign_fast32(0xc83d80, 0xc001658840, 0x0, 0x20)
   /usr/local/go/src/runtime/map_fast32.go:101 +0x303 fp=0xc001a75cc0 sp=0xc001a75c80 pc=0x4128b3
github.com/harmony-one/harmony/internal/newnode.(*NewNode).processShardInfo(0xc001674000, 0xc001a68203, 0x1e4, 0x1e4, 0x1e7)
   /mnt/go/src/github.com/harmony-one/harmony/internal/newnode/newnode.go:137 +0x37e fp=0xc001a75e28 sp=0xc001a75cc0 pc=0xa599ae
github.com/harmony-one/harmony/internal/newnode.(*NewNode).NodeHandler(0xc001674000, 0x7f08bb504da0, 0xc0019de2a0)
   /mnt/go/src/github.com/harmony-one/harmony/internal/newnode/newnode_handler.go:55 +0x8e1 fp=0xc001a75ef8 sp=0xc001a75e28 pc=0xa5a7a1
github.com/harmony-one/harmony/internal/newnode.(*NewNode).NodeHandler-fm(0x7f08bb504da0, 0xc0019de2a0)
   /mnt/go/src/github.com/harmony-one/harmony/internal/newnode/newnode.go:69 +0x3e fp=0xc001a75f20 sp=0xc001a75ef8 pc=0xa5abbe
github.com/harmony-one/harmony/p2p/host/hostv2.(*HostV2).BindHandlerAndServe.func1(0xfe69c0, 0xc0019de2a0)
   /mnt/go/src/github.com/harmony-one/harmony/p2p/host/hostv2/hostv2.go:103 +0x67 fp=0xc001a75f60 sp=0xc001a75f20 pc=0xa58257
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1(0xc00151a0e0, 0xe, 0x7f08b81da298, 0xc0019de2a0, 0x21c23, 0xc001652240)
   /mnt/go/src/github.com/libp2p/go-libp2p/p2p/host/basic/basic_host.go:299 +0x9d fp=0xc001a75fb0 sp=0xc001a75f60 pc=0xa1ba7d
runtime.goexit()
   /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc001a75fb8 sp=0xc001a75fb0 pc=0x45c1c1
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
   /mnt/go/src/github.com/libp2p/go-libp2p/p2p/host/basic/basic_host.go:257 +0x6cb
```

**Environment (please complete the following information):**
 - OS: [Linux, MacOS] Linux
- Go environment [ ```go env``` ]

**Additional context**

**Comment by LeoHChen** [comment]
newnode is not used anymore.
