### ISSUE TITLE
[release] release test 05/24

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3088]
## auto test
- [x] regression test on tx
- [x] regression test on cx
- [x] regression test on staking

## manual test
- [x] view change
- [x] state syncing

**Comment by LeoHChen** [comment]
![image](https://user-images.githubusercontent.com/4513927/82746908-a2ef8100-9d49-11ea-9043-796558634daf.png)

**Comment by LeoHChen** [comment]
![image](https://user-images.githubusercontent.com/4513927/82746925-c5819a00-9d49-11ea-96d8-57dea0c200c0.png)

**Comment by LeoHChen** [comment]
bring back the original leader.
```ec2-user@ip-172-31-37-52 testnet (master) $ node_ssh.sh 54.226.48.152 'sudo systemctl start harmony'```

![image](https://user-images.githubusercontent.com/4513927/82746954-f95cbf80-9d49-11ea-9aa7-d86fc7f1175b.png)

**Comment by LeoHChen** [comment]
leader crashed.

```
May 24 06:09:13 ip-172-31-85-251.ec2.internal harmony[8689]: panic: runtime error: invalid memory address or nil pointer dereference
May 24 06:09:13 ip-172-31-85-251.ec2.internal harmony[8689]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa608f6]
May 24 06:09:13 ip-172-31-85-251.ec2.internal harmony[8689]: goroutine 2885 [running]:
May 24 06:09:13 ip-172-31-85-251.ec2.internal harmony[8689]: github.com/harmony-one/harmony/core/types.(*Block).Header(0x0, 0xc0002de2b8)
May 24 06:09:13 ip-172-31-85-251.ec2.internal harmony[8689]: /home/ec2-user/go/src/github.com/harmony-one/harmony/core/types/block.go:523 +0x26
May 24 06:09:13 ip-172-31-85-251.ec2.internal harmony[8689]: github.com/harmony-one/harmony/core.(*BlockValidator).ValidateHeader(0xc0000a09e0, 0x0, 0xc0000a0901, 0xc000b28960, 0xc000b2
May 24 06:09:13 ip-172-31-85-251.ec2.internal harmony[8689]: /home/ec2-user/go/src/github.com/harmony-one/harmony/core/block_validator.go:128 +0x2b
May 24 06:09:13 ip-172-31-85-251.ec2.internal harmony[8689]: github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyV2.func1(0xc00661baa0, 0xc00661ba40, 0xc0004d2960, 0xc0003d
May 24 06:09:13 ip-172-31-85-251.ec2.internal harmony[8689]: /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_newblock.go:57 +0x20e
May 24 06:09:13 ip-172-31-85-251.ec2.internal harmony[8689]: created by github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyV2
May 24 06:09:13 ip-172-31-85-251.ec2.internal harmony[8689]: /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_newblock.go:28 +0x5d
May 24 06:09:13 ip-172-31-85-251.ec2.internal harmony[8689]: node.sh: node process finished with status 2
May 24 06:09:13 ip-172-31-85-251.ec2.internal harmony[8689]: node.sh: exiting
```

**Comment by LeoHChen** [comment]
updated the crashed node with new version with the fix and no crash anymore.

**Comment by LeoHChen** [comment]
However, the node 54.226.48.152 is not able to catch up with syncing anymore. I have restarted the node a few times and it still failed to sync.

![image](https://user-images.githubusercontent.com/4513927/82748620-798a2180-9d58-11ea-8b7f-fdca32d48cac.png)

**Comment by LeoHChen** [comment]
Found another crash,

```
May 24 07:51:28 ip-172-31-85-251.ec2.internal harmony[11205]: panic: runtime error: invalid memory address or nil pointer dereference
May 24 07:51:28 ip-172-31-85-251.ec2.internal harmony[11205]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa60bd6]
May 24 07:51:28 ip-172-31-85-251.ec2.internal harmony[11205]: goroutine 178 [running]:
May 24 07:51:28 ip-172-31-85-251.ec2.internal harmony[11205]: github.com/harmony-one/harmony/core/types.(*Block).Header(0x0, 0xb255e8)
May 24 07:51:28 ip-172-31-85-251.ec2.internal harmony[11205]: /home/leochen/go/src/github.com/harmony-one/harmony/core/types/block.go:523 +0x26
May 24 07:51:28 ip-172-31-85-251.ec2.internal harmony[11205]: github.com/harmony-one/harmony/core.(*BlockValidator).ValidateHeader(0xc0003c91a0, 0x0, 0xc0003c9101, 0xc
May 24 07:51:28 ip-172-31-85-251.ec2.internal harmony[11205]: /home/leochen/go/src/github.com/harmony-one/harmony/core/block_validator.go:128 +0x2f
May 24 07:51:28 ip-172-31-85-251.ec2.internal harmony[11205]: github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyV2.func1(0xc00052bbc0, 0xc00052bb60, 0xc
May 24 07:51:28 ip-172-31-85-251.ec2.internal harmony[11205]: /home/leochen/go/src/github.com/harmony-one/harmony/node/node_newblock.go:57 +0x20e
May 24 07:51:28 ip-172-31-85-251.ec2.internal harmony[11205]: created by github.com/harmony-one/harmony/node.(*Node).WaitForConsensusReadyV2
May 24 07:51:28 ip-172-31-85-251.ec2.internal harmony[11205]: /home/leochen/go/src/github.com/harmony-one/harmony/node/node_newblock.go:28 +0x5d
```

**Comment by LeoHChen** [comment]
finally fixed the crash with this PR, https://github.com/harmony-one/harmony/pull/3091

**Comment by LeoHChen** [comment]
after block sync, still, see this error
```
{"level":"error","port":"9000","ip":"54.226.48.152","error":"GetLastCommitSig failed with wrong number of committed message 0","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_newblock.go:232","time":"2020-05-24T08:03:34.238479848Z","message":"[proposeNewBlock] Cannot get commit signatures from last block"}
{"level":"error","port":"9000","ip":"54.226.48.152","error":"GetLastCommitSig failed with wrong number of committed message 0","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_newblock.go:54","time":"2020-05-24T08:03:34.238497636Z","message":"!!!!!!!!!Failed Proposing New Block!!!!!!!!!"}
{"level":"error","port":"9000","ip":"54.226.48.152","error":"block is nil","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_newblock.go:72","time":"2020-05-24T08:03:34.23850701Z","message":"!!!!!!!!!Failed Verifying New Block Header!!!!!!!!!"}
{"level":"info","port":"9000","ip":"54.226.48.152","blockNum":52744,"caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_newblock.go:50","time":"2020-05-24T08:03:34.258594526Z","message":"PROPOSING NEW BLOCK ------------------------------------------------"}
```

**Comment by LeoHChen** [comment]
```
{"level":"info","port":"9000","ip":"54.226.48.152","myBlock":52773,"myViewID":52795,"phase":0,"mode":"Normal","Mode":"Normal","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:395","time":"2020-05-24T08:07:13.921880343Z","message":"Node is IN SYNC"}
{"level":"info","port":"9000","ip":"54.226.48.152","myBlock":52773,"myViewID":52795,"phase":0,"mode":"Normal","MsgBlockNum":52774,"MsgViewID":52796,"caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/validator.go:103","time":"2020-05-24T08:07:18.665831022Z","message":"[OnPrepared] Received prepared message"}
{"level":"error","port":"9000","ip":"54.226.48.152","myBlock":52773,"myViewID":52795,"phase":0,"mode":"Normal","error":"unknown ancestor","inChain":"52772","MsgBlockNum":"52774","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/checks.go:176","time":"2020-05-24T08:07:18.668612324Z","message":"[OnPrepared] Block header is not verified successfully"}
{"level":"info","port":"9000","ip":"54.226.48.152","myBlock":52773,"myViewID":52795,"phase":0,"mode":"Normal","MsgBlockNum":52775,"MsgViewID":52797,"caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/validator.go:103","time":"2020-05-24T08:07:26.744027645Z","message":"[OnPrepared] Received prepared message"}
{"level":"error","port":"9000","ip":"54.226.48.152","myBlock":52773,"myViewID":52795,"phase":0,"mode":"Normal","error":"unknown ancestor","inChain":"52772","MsgBlockNum":"52775","caller":"/home/leochen/go/src/github.com/harmony-one/harmony/consensus/checks.go:176","time":"2020-05-24T08:07:26.746842419Z","message":"[OnPrepared] Block header is not verified successfully"}

```

**Comment by LeoHChen** [comment]
The node finally caught up, saw BINGO!

**Comment by LeoHChen** [comment]
I'll update the LRTN with the new code including my PR and test view change again.

**Comment by LeoHChen** [comment]
Stopped the leader of shard1.

![image](https://user-images.githubusercontent.com/4513927/82749175-3336c180-9d5c-11ea-926e-26f615a3168e.png)

**Comment by LeoHChen** [comment]
leader change succeeded on shard1.

![image](https://user-images.githubusercontent.com/4513927/82749207-68431400-9d5c-11ea-8531-ce314cde00a7.png)

**Comment by LeoHChen** [comment]
restart the node

**Comment by LeoHChen** [comment]
node can join back consensus.

**Comment by LeoHChen** [comment]
https://jenkins.harmony.one/job/regression_test/38/console
s3://unique-bucket-bin/tests/regression/testnet/2020-05-23-10-29-35-UTC.csv 

https://jenkins.harmony.one/job/regression_test/39/console
s3://unique-bucket-bin/tests/regression/testnet/2020-05-24-06-07-13-UTC.csv

**Comment by LeoHChen** [comment]
Test is finished, ready to merge master to t3.
