### ISSUE TITLE
RPC failed to respond after successful node restart

### ISSUE THREAD

**Issue by Daniel-VDM** [harmony-one/harmony#3151]
During the nightly regression test on testnet, a snapshot of the DB is done. This process involves shutting down the harmony process, making a copy of the harmony DB, and restarting the harmony process. Verification is done at the end to ensure that the node resumes making progress. This verification relies on the latest-header RPC, but the RPC fails to respond.

Stack trace from Jenkins job (time in UTC)
```
12:49:32  Traceback (most recent call last):
12:49:32    File "./snapshot.py", line 452, in _is_progressed_node
12:49:32      start_header = blockchain.get_latest_header(f"http://{machine['ip']}:9500/")
12:49:32    File "/home/snapshot/.local/lib/python3.7/site-packages/pyhmy/blockchain.py", line 289, in get_latest_header
12:49:32      return rpc_request('hmy_latestHeader', endpoint=endpoint, timeout=timeout)['result']
12:49:32    File "/home/snapshot/.local/lib/python3.7/site-packages/pyhmy/rpc/request.py", line 107, in rpc_request
12:49:32      raw_resp = base_request(method, params, endpoint, timeout)
12:49:32    File "/home/snapshot/.local/lib/python3.7/site-packages/pyhmy/rpc/request.py", line 67, in base_request
12:49:32      raise RequestsError(endpoint) from err
12:49:32  pyhmy.rpc.exceptions.RequestsError: Error connecting to http://3.84.58.192:9500/
12:49:32  
12:49:32  error on RPC from 3.84.58.192. Error Error connecting to http://3.84.58.192:9500/
12:49:32  Traceback (most recent call last):
12:49:32    File "./snapshot.py", line 541, in <module>
12:49:32      raise RuntimeError(f"one or more node did not make progress after being started...")
12:49:32  RuntimeError: one or more node did not make progress after being started...
12:49:32  
```

However, when looking at the journal on the machine that failed we see that the node started fine.(time in UTC)
```
Jun 10 01:06:23 ip-172-31-88-178.ec2.internal harmony[31115]: My Genesis Account: one14rujvdv383r90s2qer05jf5zwk5n4slr5h5syr/cc29030fd7888a9f2aa1176ae972787a87295aae79149e83e2113e4d71f49d473fa3bd89e8db968b8a42141d4673e918:0
Jun 10 01:06:23 ip-172-31-88-178.ec2.internal harmony[31115]: Legacy mode; node key 8a211eb5e9334341fd2498fb5d6b922b4a0984d6a4ea0b5631c1904de5fe21fd6889c9c032d862546ca50a5c41294b0c;ba27796a04c1e4d2cb2d946ac520c2b41589517cb9ae22e64718086c1b13bec1c3d1d78c27
Jun 10 12:49:14 ip-172-31-88-178.ec2.internal systemd[1]: Stopping harmony service...
Jun 10 12:49:14 ip-172-31-88-178.ec2.internal harmony[31115]: Got terminated signal. Gracefully shutting down...
Jun 10 12:49:14 ip-172-31-88-178.ec2.internal harmony[31115]: Successfully shut down!
Jun 10 12:49:14 ip-172-31-88-178.ec2.internal harmony[31115]: node.sh: received SIGTERM
Jun 10 12:49:14 ip-172-31-88-178.ec2.internal systemd[1]: Stopped harmony service.
Jun 10 12:49:18 ip-172-31-88-178.ec2.internal systemd[1]: Started harmony service.
Jun 10 12:49:18 ip-172-31-88-178.ec2.internal systemd[1]: Starting harmony service...
Jun 10 12:49:18 ip-172-31-88-178.ec2.internal harmony[1517]: node.sh: binaries did not change
Jun 10 12:49:18 ip-172-31-88-178.ec2.internal harmony[1517]: node.sh: public IP address autodetected: 3.84.58.192
Jun 10 12:49:18 ip-172-31-88-178.ec2.internal harmony[1517]: node.sh: ############### Running Harmony Process ###############
Jun 10 12:49:18 ip-172-31-88-178.ec2.internal harmony[1517]: My Genesis Account: one1dpm37ppsgvepjfyvsamas25md280ctgmcfjlfx/8a211eb5e9334341fd2498fb5d6b922b4a0984d6a4ea0b5631c1904de5fe21fd6889c9c032d862546ca50a5c41294b0c:0
Jun 10 12:49:18 ip-172-31-88-178.ec2.internal harmony[1517]: My Genesis Account: one17hlq693v48gy9snnhvd7cuvl8g9nkakgaf3pya/ba27796a04c1e4d2cb2d946ac520c2b41589517cb9ae22e64718086c1b13bec1c3d1d78c274d4ffafd78e1b66705e496:0
Jun 10 12:49:18 ip-172-31-88-178.ec2.internal harmony[1517]: My Genesis Account: one14rujvdv383r90s2qer05jf5zwk5n4slr5h5syr/cc29030fd7888a9f2aa1176ae972787a87295aae79149e83e2113e4d71f49d473fa3bd89e8db968b8a42141d4673e918:0
Jun 10 12:49:18 ip-172-31-88-178.ec2.internal harmony[1517]: Legacy mode; node key 8a211eb5e9334341fd2498fb5d6b922b4a0984d6a4ea0b5631c1904de5fe21fd6889c9c032d862546ca50a5c41294b0c;ba27796a04c1e4d2cb2d946ac520c2b41589517cb9ae22e64718086c1b13bec1c3d1d78c274
Jun 10 17:29:35 ip-172-31-88-178.ec2.internal systemd[1]: Stopping harmony service...
Jun 10 17:29:35 ip-172-31-88-178.ec2.internal harmony[1517]: Got terminated signal. Gracefully shutting down...
```

Infact, when checking the logs, we see that the node still participates in consensus. 
```
{"level":"info","port":"9000","ip":"3.84.58.192","blockNum":130952,"epochNum":3446,"ViewId":130952,"blockHash":"0xc77c9e339bda269b791cf7a29ac7518fb83d1479565c5534239f1dc5d1b374d6","numTxns":0,"numStakingTxns":0,"numSignatures":3,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:429","time":"2020-06-10T12:51:01.815872837Z","message":"BINGO !!! Reached Consensus"}
```

**Comment by rlan35** [comment]
this issue may be stale. closing for now. Feel free to reopen.
