### ISSUE TITLE
segfault during state syncing

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#322]
**Describe the bug**
I launched a new devnet and started to join new node.  I saw a few existing nodes hit the following segfault.

```
2019/01/25 00:20:20 Command running ./harmony [-ip 34.227.99.90 -port 9000 -log_folder ../tmp_log/log-20190125.002110 -attacked_mode 0 -bc_addr /ip4/54.183.5.66/tcp/9999/ipfs/QmdQVypu6NSm7m8bNZj5EJCnjPhXR8QyRmDnDBidxGaHWi -min_peers 20 -metrics_report_url http://54.213.59.51:3000/report]
2019/01/25 07:00:24 Stderr 2019/01/25 07:00:24 [SYNC] unable to send new block to unsync node with error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 52.0.5.4:6000: i/o timeout"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb77086]

goroutine 2579 [running]:
github.com/harmony-one/harmony/node.(*Node).SendNewBlockToUnsync(0xc42018a240)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node.go:608 +0x5d6
created by github.com/harmony-one/harmony/node.(*Node).SupportSyncing
        /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node.go:487 +0xc2
2019/01/25 07:00:24 Command finished with error: exit status 2
```

**To Reproduce**
Launch a new devnet on AWS.

**Expected behavior**
No crash. 

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux, MacOS] Linux
- Go environment [ ```go env``` ]

**Additional context**

All logs are available at 
https://s3.console.aws.amazon.com/s3/buckets/harmony-benchmark/logs/20190125.002110/?region=us-west-2&tab=overview

**Comment by chaosma** [comment]
https://github.com/harmony-one/harmony/pull/332
