### ISSUE TITLE
[STN] During the view change, node panic and exited.

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#3557]
### Describe the bug

When testing on stress net, following panic log is observed during view change and cause the node being terminated. 

```
Feb 28 23:15:32 ip-172-26-21-217 harmony[917611]: panic: assignment to entry in nil map
Feb 28 23:15:32 ip-172-26-21-217 systemd[1]: harmony.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 28 23:15:32 ip-172-26-21-217 harmony[917611]: goroutine 1543 [running]:
Feb 28 23:15:32 ip-172-26-21-217 harmony[917611]: github.com/harmony-one/harmony/consensus.(*viewChange).InitPayload(0xc000de7200, 0xc00007ceb0, 0x895b, 0x801e, 0xc0002b8710, 0x1, 0x1, 0x60, 0x1f)
Feb 28 23:15:32 ip-172-26-21-217 harmony[917611]:         /home/yx/go/src/github.com/harmony-one/harmony/consensus/view_change_construct.go:424 +0x786
Feb 28 23:15:32 ip-172-26-21-217 harmony[917611]: github.com/harmony-one/harmony/consensus.(*Consensus).startViewChange(0xc000281b00)
Feb 28 23:15:32 ip-172-26-21-217 harmony[917611]:         /home/yx/go/src/github.com/harmony-one/harmony/consensus/view_change.go:264 +0x56b
Feb 28 23:15:32 ip-172-26-21-217 harmony[917611]: github.com/harmony-one/harmony/consensus.(*Consensus).Start.func1(0xc000281b00, 0xc000bda780, 0xc0017a1ce0, 0xc000bda5a0, 0xc0017a1c80)
Feb 28 23:15:32 ip-172-26-21-217 harmony[917611]:         /home/yx/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:334 +0x5db
Feb 28 23:15:32 ip-172-26-21-217 harmony[917611]: created by github.com/harmony-one/harmony/consensus.(*Consensus).Start
Feb 28 23:15:32 ip-172-26-21-217 harmony[917611]:         /home/yx/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:287 +0x67
```

**Comment by LeoHChen** [comment]
Is your code based on the latest code?  This error was seen before I remember.

**Comment by JackyWYX** [comment]
It is rebased on v3.1.2, released on 02/25/2021

**Comment by rlan35** [comment]
do we know why it's uninitialized? I thought AddViewIDKeyIfNotExist() always initialize them before usage?

**Comment by LeoHChen** [comment]
I think it is because of consensus.ResetViewChangeState  was not protected by mutex within UpdatePublicKeys.  Also, consensus.ResetState is not protected by any mutex within UpdatePublicKeys.  There are race condition there.  @rlan35 , what do you think? The UpdatePublicKeys should probably be protected by consensus.mutex.

**Comment by JackyWYX** [comment]
@LeoHChen Can we close this for now?
