### ISSUE TITLE
OOM in explorer node

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3668]
**Describe the bug**
I've noticed the OOM killer killed the harmony process on explorer nodes on mainnet.

Run `journalctl -eu harmony` and you can see the crash logs. 

Some excerpt of the crash log,
```
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]: goroutine 103617423 [semacquire]:
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]: sync.runtime_SemacquireMutex(0xc00029a534, 0xc091cd8b00, 0x0)
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]:         /opt/hostedtoolcache/go/1.14.14/x64/src/runtime/sema.go:71 +0x47
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]: sync.(*RWMutex).RLock(...)
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]:         /opt/hostedtoolcache/go/1.14.14/x64/src/sync/rwmutex.go:50
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]: github.com/libp2p/go-libp2p-swarm.(*Swarm).notifyAll(0xc00029a480, 0xc077ddcfe0)
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]:         /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.4.0/swarm.go:488 +0x1a5
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]: github.com/libp2p/go-libp2p-swarm.(*Stream).remove.func1(0xc02de72d90)
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]:         /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.4.0/swarm_stream.go:115 +0xab
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]: created by github.com/libp2p/go-libp2p-swarm.(*Stream).remove
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]:         /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.4.0/swarm_stream.go:111 +0x56
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]: goroutine 103617424 [semacquire]:
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]: sync.runtime_SemacquireMutex(0xc00029a534, 0xc091cd8b00, 0x0)
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]:         /opt/hostedtoolcache/go/1.14.14/x64/src/runtime/sema.go:71 +0x47
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]: sync.(*RWMutex).RLock(...)
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]:         /opt/hostedtoolcache/go/1.14.14/x64/src/sync/rwmutex.go:50
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]: github.com/libp2p/go-libp2p-swarm.(*Swarm).notifyAll(0xc00029a480, 0xc077ddcff0)
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]:         /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.4.0/swarm.go:488 +0x1a5
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]: github.com/libp2p/go-libp2p-swarm.(*Stream).remove.func1(0xc053d40460)
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]:         /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.4.0/swarm_stream.go:115 +0xab
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]: created by github.com/libp2p/go-libp2p-swarm.(*Stream).remove
Apr 21 21:44:30 explorer-node-s3-e0 harmony-explorer-node[9029]:         /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.4.0/swarm_stream.go:111 +0x56
```

Another one
```
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: github.com/harmony-one/harmony/p2p/stream/protocols/sync.(*syncStream).handleRespLoop(0xc0000d3680)
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: /mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/stream.go:136 +0xd0
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: created by github.com/harmony-one/harmony/p2p/stream/protocols/sync.(*syncStream).run
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: /mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/stream.go:64 +0x19d
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: goroutine 1031 [select, 17903 minutes]:
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: github.com/libp2p/go-libp2p/p2p/protocol/identify.(*peerHandler).loop(0xc008ed42a0, 0x1ee3140, 0xc008e8cb00, 0xc008e87ea0)
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: /var/lib/jenkins/go/pkg/mod/github.com/libp2p/go-libp2p@v0.13.0/p2p/protocol/identify/peer_loop.go:92 +0x144
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: created by github.com/libp2p/go-libp2p/p2p/protocol/identify.(*peerHandler).start
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: /var/lib/jenkins/go/pkg/mod/github.com/libp2p/go-libp2p@v0.13.0/p2p/protocol/identify/peer_loop.go:74 +0x9b
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: goroutine 872 [select, 17903 minutes]:
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: github.com/harmony-one/harmony/p2p/stream/protocols/sync.(*syncStream).handleRespLoop(0xc0000d3720)
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: /mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/stream.go:136 +0xd0
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: created by github.com/harmony-one/harmony/p2p/stream/protocols/sync.(*syncStream).run
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: /mnt/jenkins/workspace/harmony-release/harmony/p2p/stream/protocols/sync/stream.go:64 +0x19d
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: goroutine 869 [select, 64 minutes]:
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: github.com/libp2p/go-yamux/v2.(*Session).AcceptStream(0xc008843860, 0xc1424c8f20, 0x0, 0x4490ee)
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: /var/lib/jenkins/go/pkg/mod/github.com/libp2p/go-yamux/v2@v2.0.0/session.go:229 +0x116
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: github.com/libp2p/go-libp2p-yamux.(*conn).AcceptStream(0xc008843860, 0xc008f09f78, 0x18, 0xc008e96f00, 0x101ec99)
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: /var/lib/jenkins/go/pkg/mod/github.com/libp2p/go-libp2p-yamux@v0.5.1/conn.go:35 +0x2b
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: github.com/libp2p/go-libp2p-swarm.(*Conn).start.func1(0xc008cb8c80)
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: /var/lib/jenkins/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.4.0/swarm_conn.go:107 +0xe0
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: created by github.com/libp2p/go-libp2p-swarm.(*Conn).start
Apr 18 14:39:10 ip-172-31-50-31.ec2.internal harmony[19814]: /var/lib/jenkins/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.4.0/swarm_conn.go:102 +0x3f
```

```
>> dmesg | grep harmony

[14187400.293169] harmony invoked oom-killer: gfp_mask=0x14201ca(GFP_HIGHUSER_MOVABLE|__GFP_COLD), nodemask=(null),  order=0, oom_score_adj=0
[14187400.330965] harmony cpuset=/ mems_allowed=0
[14187400.339153] CPU: 0 PID: 11004 Comm: harmony Not tainted 4.14.193-149.317.amzn2.x86_64 #1
[14187401.365442] [10890]  1000 10890  1339945   940203    1904       9        0             0 harmony
[14187401.394743] Out of memory: Kill process 10890 (harmony) score 933 or sacrifice child
[14187401.402609] Killed process 10890 (harmony) total-vm:5359780kB, anon-rss:3760812kB, file-rss:0kB, shmem-rss:0kB
[14187402.416438] oom_reaper: reaped process 10890 (harmony), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

```

I've uploaded the full crash log returned from journalctl to the s3 bucket.

**Comment by LeoHChen** [comment]
full crash log uploaded to s3://haochen-harmony-pub/debug/3668/c.log.gz, and s3://haochen-harmony-pub/debug/3668/c1.log.gz

**Comment by LeoHChen** [comment]
uploaded some more full logs to 
`s3://haochen-harmony-pub/debug/3668/crash.log.gz`
`s3://haochen-harmony-pub/debug/3668/crash-g.log.gz`

**Comment by LeoHChen** [comment]
I think we've found a way to reproduce the OOM.  Moving the ticket to private repo now.
