### ISSUE TITLE
test and rollout stream syncing on mainnet

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3685]
## Summary

The stream syncing code is already released to mainnet, we need to roll out this feature after extensive testing.

### configuration
The following section is the configuration of syncing.
```
[Sync]
  Concurrency = 6
  DiscBatch = 8
  DiscHardLowCap = 6
  DiscHighCap = 128
  DiscSoftLowCap = 8
  Downloader = false
  InitStreams = 8
  LegacyClient = true
  LegacyServer = true
  LegacyServerPort = 6000
  MinPeers = 6
```

To enable the stream syncing, please change two configuration variables to 
```
  Downloader = true
  LegacyClient = false
```

## Test Scenario
The following scenarios need to be tested on the testnet and mainnet after enabling the stream syncing.

### test cases
1. a new external validator node sync from the genesis block
1. a new external explorer node sync from the genesis block
1. an existing external validator node continues doing syncing and consensus after enabling stream syncing
1. an existing external explorer node continues doing syncing after enabling stream syncing
1. a new harmony internal node sync from the genesis block
1. an existing harmony internal node continues doing syncing and consensus after enabling stream syncing

### testnet
In addition to the above tests, on the testnet, we also need to test restart the entire shard after enabling the stream syncing, which means testing the bootstrap process of the stream syncing.

1. remove the DNS server setting on testnet; after the stream syncing is enabled by default.
1. restart the entire shard/network on testnet

### mainnet
On mainnet, just test the above 6 test cases.

## monitoring and report
During the test, please keep monitoring the CPU and Memory consumption of the node, and report any abnormality during the test, with comparison to the original DNS syncing.

Please report and crash or bug found during the test in this ticket.

**Comment by sophoah** [comment]
@JackyWYX I tested a brand new shard 3 node starting sync from 0 configured with stream sync and having a SIGSEV

```
May 02 10:15:20 Pangaea_Testnet_S3_US systemd[1]: Started harmony service.
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]: Staking mode; node key bafd2e3fa573cf2b6534768aee322a06310b49092a0bc57bab429b692bf745413cef77c05468a54b905026e2c7154893; -> shard 3
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]: panic: runtime error: invalid memory address or nil pointer dereference
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12d3910]
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]: goroutine 1 [running]:
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]: github.com/harmony-one/harmony/node.(*Node).createStateSync(0xc000435080, 0x1baf820)
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]:         /mnt/jenkins/workspace/harmony-release/harmony/node/node_syncing.go:90 +0x30
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]: github.com/harmony-one/harmony/node.(*Node).supportSyncing(0xc000435080)
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]:         /mnt/jenkins/workspace/harmony-release/harmony/node/node_syncing.go:337 +0xaa
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]: github.com/harmony-one/harmony/node.(*Node).StartGRPCSyncClient(0xc000435080)
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]:         /mnt/jenkins/workspace/harmony-release/harmony/node/node_syncing.go:318 +0x52
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]: main.setupNodeAndRun(0xc0007bcc88, 0x5, 0xc0007bd980, 0x9, 0x0, 0xffffffffffffffff, 0x0, 0xc0007bd5bc, 0x2, 0xc00081c5a0, ...)
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]:         /mnt/jenkins/workspace/harmony-release/harmony/cmd/harmony/main.go:379 +0x17f8
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]: main.runHarmonyNode(0x2e511c0, 0xc00084c480, 0x0, 0x2)
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]:         /mnt/jenkins/workspace/harmony-release/harmony/cmd/harmony/main.go:134 +0x26e
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]: github.com/spf13/cobra.(*Command).execute(0x2e511c0, 0xc000194160, 0x2, 0x2, 0x2e511c0, 0xc000194160)
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]:         /var/lib/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]: github.com/spf13/cobra.(*Command).ExecuteC(0x2e511c0, 0x0, 0x1, 0xc000182058)
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]:         /var/lib/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]: github.com/spf13/cobra.(*Command).Execute(...)
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]:         /var/lib/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]: main.main()
May 02 10:15:21 Pangaea_Testnet_S3_US harmony[32215]:         /mnt/jenkins/workspace/harmony-release/harmony/cmd/harmony/main.go:105 +0x2d
May 02 10:15:21 Pangaea_Testnet_S3_US systemd[1]: harmony.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 02 10:15:21 Pangaea_Testnet_S3_US systemd[1]: harmony.service: Failed with result 'exit-code'.
May 02 10:15:22 Pangaea_Testnet_S3_US systemd[1]: harmony.service: Service hold-off time over, scheduling restart.
May 02 10:15:22 Pangaea_Testnet_S3_US systemd[1]: harmony.service: Scheduled restart job, restart counter is at 30.
```

**Comment by sophoah** [comment]
@JackyWYX @LeoHChen just a quick update here
- the latest update `version v7011-v4.0.1-12-gd8b5d169` fixed the panic error
- tested on a brand new node with DB starting from 0  (test 1) 
- in 1h observation, normal validator synced 460k blocks (non beacon shard) and 260k blocks (beacon shard)
- tested on an existing external validator node with BINGO (test 3)
  - enable stream sync and confirmed BINGO
  - stopped external node for 2 min, restarted it and confirmed BINGO

Now you asked for a config that wasn't proposed by @LeoHChen `legacyServer = false`. I tested with that but i didn't change `legacyClient` So the testing above was done with `Downloader = true` `LegacyClient = true` and `LegacyServer = false`

I will do the same above now with  `Downloader = true` `LegacyClient = false` and `LegacyServer = false`

Note that the test above was done with a node that when stopped the consensus was loss, so there was actually no sync process. I repeated the test on a different shard and now with `LegacyClient = false`, the DB stopped syncing. after multiple harmony process restart and waiting for a while, the beacon shard chain start to sync but the shard chain is still stuck. I can restart the sync properly when I changed the `LegacyClient` back to true

While writing the above, it took easily another 3 min and now it seems to work ... so waiting fixed the issues ... not sure why it doesn't sync right away.

Test 1 and test 3 are ok.

Suggestion: 
Can you add a new field in the hmy utility metadata to inform the operational state of the sync ie streaming or not

**Comment by sophoah** [comment]
@LeoHChen @JackyWYX could you guys please help out with the actual config for stream sync ? would be nice to have it configured in one parameter, having 3 modify is a pain, i have that currently in my jinja2 : 
```
{% if enable_streamsync_var == "false" %}
  LegacyClient = true
  LegacyServer = true
  Downloader = false
{% else %}
  LegacyClient = false
  LegacyServer = false
  Downloader = true
{% endif %}
```

**Comment by sophoah** [comment]
@JackyWYX do you see any reason why the shard 2 node is stuck ? https://pastebin.com/7EJgWVAU only the beacon shard chain is syncing via streamsync.

**Comment by sophoah** [comment]
@JackyWYX Problem 2 : the external full node sync managed to fully synced his shard (in less than 24h, more than 9m blocks), however the beacon shard chain sync is stuck at block 1413699. Here is the logs : https://pastebin.com/ywqMy2Jz . I am seeing a BAD BLOCK error. Note that the node is not supposed to BINGO, just for the sake of testing a sync from block 0

**Comment by sophoah** [comment]
test 2 and test 5 in progress, both node are currently syncing

**Comment by sophoah** [comment]
@JackyWYX test 5 is running on shard 1 and, sync from block 0 of the shard chain is currently stuck at block 1638608 (shard chain still going)

**Comment by sophoah** [comment]
@JackyWYX this is just to report but shard 2 explorer node had streamsync enabled. Without any apparent reason, the node got stuck until i restarted the node for it to work.  here are the logs before the restart : https://pastebin.com/tsNG5ztr

**Comment by LeoHChen** [comment]
@sophoah , have you started testing on mainnet?

**Comment by sophoah** [comment]
@JackyWYX testnet explorer was stuck in view change mode due to an external validator stuck with streamsync enabled

here are some of the logs captured
```
{"level":"error","module":"downloader","mode":"short range","error":"context deadline exceeded","caller":"/mnt/jenkins/workspace/harmony-release/harmony/hmy/downloader/shortrange.go:163","time":"2021-05-23T18:15:06.521004279+02:00","message":"getBlocksByHashes worker failed"}
{"level":"warn","module":"downloader","mode":"short range","error":"context deadline exceeded","stream":"","caller":"/mnt/jenkins/workspace/harmony-release/harmony/hmy/downloader/shortrange.go:226","time":"2021-05-23T18:15:06.521021231+02:00","message":"failed to getBlockByHashes"}
{"level":"error","module":"downloader","mode":"short range","error":"context deadline exceeded","caller":"/mnt/jenkins/workspace/harmony-release/harmony/hmy/downloader/shortrange.go:163","time":"2021-05-23T18:15:06.521025489+02:00","message":"getBlocksByHashes worker failed"}
{"level":"warn","module":"downloader","mode":"short range","error":"context deadline exceeded","stream":"","caller":"/mnt/jenkins/workspace/harmony-release/harmony/hmy/downloader/shortrange.go:226","time":"2021-05-23T18:15:06.521041307+02:00","message":"failed to getBlockByHashes"}
{"level":"error","module":"downloader","mode":"short range","error":"context deadline exceeded","caller":"/mnt/jenkins/workspace/harmony-release/harmony/hmy/downloader/shortrange.go:163","time":"2021-05-23T18:15:06.521045545+02:00","message":"getBlocksByHashes worker failed"}
```

a restart of the harmony binary fixed the issue

**Comment by JB273** [comment]
Did test no. 3 on testnet, this was successful.

**Comment by JB273** [comment]
@LeoHChen How can we test the stream syncing on mainnet?

**Comment by sophoah** [comment]
@JB273 we can discuss but i don't think streamsync is ready for mainnet yet

**Comment by LeoHChen** [comment]
This is paused, not ready for mainnet yet. Change it to low priority for now.
