### ISSUE TITLE
Index out of range panic in quorum

### ISSUE THREAD

**Issue by MaxMustermann2** [harmony-one/harmony#4340]
- Shards 3 and 1 went offline due to an index out of range error.
 - Not all nodes were affected. 
 - Affected nodes continued as expected, however, voting power and thus consensus was lost.
 - The affected nodes were used for DNS sync as well. After the crash, the affected nodes synced amongst themselves (and so did the external validators) to produce a forked chain. This forked chain needed a revert on all (internal + external) nodes.

```log
Jan 17 06:42:35 harmony[1239498]: panic: runtime error: index out of range [-12]
Jan 17 06:42:35 harmony[1239498]: goroutine 1562 [running]:
Jan 17 06:42:35 harmony[1239498]: github.com/harmony-one/harmony/consensus/quorum.(*cIdentities).NthNextHmy(0xc001267bd0, {0x232f680, 0xc0000ace60}, 0x99fa4d?, 0xffffffffffff8006)
Jan 17 06:42:35 harmony[1239498]:         /home/runner/work/harmony/harmony/harmony/consensus/quorum/quorum.go:234 +0x153
Jan 17 06:42:35 harmony[1239498]: github.com/harmony-one/harmony/consensus.(*Consensus).getNextLeaderKey(0xc00035c000, 0x2597307)
Jan 17 06:42:35 harmony[1239498]:         /home/runner/work/harmony/harmony/harmony/consensus/view_change.go:224 +0x646
Jan 17 06:42:35 harmony[1239498]: github.com/harmony-one/harmony/consensus.(*Consensus).startViewChange(0xc00035c000)
Jan 17 06:42:35 harmony[1239498]:         /home/runner/work/harmony/harmony/harmony/consensus/view_change.go:268 +0x1af
Jan 17 06:42:35 harmony[1239498]: github.com/harmony-one/harmony/consensus.(*Consensus).Start.func1()
Jan 17 06:42:35 harmony[1239498]:         /home/runner/work/harmony/harmony/harmony/consensus/consensus_v2.go:353 +0x1008
Jan 17 06:42:35 harmony[1239498]: created by github.com/harmony-one/harmony/consensus.(*Consensus).Start
Jan 17 06:42:35 harmony[1239498]:         /home/runner/work/harmony/harmony/harmony/consensus/consensus_v2.go:294 +0xca
```

**Comment by MaxMustermann2** [comment]
Temporarily resolved by installing timesync services facing public NTP servers on all of our nodes. Needs to be fixed by removing the fallback view ID function entirely.
