### ISSUE TITLE
v2023.4.0-0 panic: insertChain failed to update current block

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#4616]
**Describe the bug**

node crashed with the below error
```
panic: insertChain failed to update current block
goroutine 52315598 [running]:
github.com/harmony-one/harmony/core.(*BlockChainImpl).InsertChain(0xc000d78000, {0xc0239b30c8, 0x1, 0x1}, 0x60?)
        /root/go/src/github.com/harmony-one/harmony/core/blockchain_impl.go:1648 +0x4c6
github.com/harmony-one/harmony/consensus.(*Consensus).preCommitAndPropose.func1()
        /root/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:580 +0x39b
created by github.com/harmony-one/harmony/consensus.(*Consensus).preCommitAndPropose
        /root/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:561 +0x46a
```
happening on v8194-v2023.4.0-0-g3e7ff383

**To Reproduce**

undetermined

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by sophoah** [comment]
fixed in #4612
