### ISSUE TITLE
segmentation violation on v8329-v2023.4.2-133-gfe78ba07

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#4646]
**Describe the bug**
shard 1 devnet with leader rotation activated faced a segmentation fault after deletion of the shard 0 DB and restart

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1aa075f]
goroutine 2436 [running]:
github.com/harmony-one/harmony/consensus.(*Consensus).isLeader(0x22?)
        /root/go/src/github.com/harmony-one/harmony/consensus/consensus_service.go:491 +0x1f
github.com/harmony-one/harmony/consensus.(*Consensus).StartChannel(0xc00d3f8f00)
        /root/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:332 +0x36
github.com/harmony-one/harmony/node.(*Node).BootstrapConsensus.func2()
        /root/go/src/github.com/harmony-one/harmony/node/node_handler.go:437 +0x25
created by github.com/harmony-one/harmony/node.(*Node).BootstrapConsensus
        /root/go/src/github.com/harmony-one/harmony/node/node_handler.go:436 +0x1af
```
**To Reproduce**
1. stop harmony process
2. delete sard 0 DB
3. start harmony process

**Comment by Frozen** [comment]
Fixed by #4684. The consensus leader check now safely handles an unknown/nil leader key. Closing as completed.
