### ISSUE TITLE
node crash in testnet

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#564]
**Describe the bug**

Seven nodes on testnet crashed with the same error message.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x796a52]

goroutine 51028 [running]:
github.com/harmony-one/bls/ffi/go/bls.(*Sign).Serialize(0x0, 0xc002a37430, 0x4, 0x10)
 /home/ec2-user/go/src/github.com/harmony-one/bls/ffi/go/bls/bls.go:262 +0x22
github.com/harmony-one/harmony/consensus.(*Consensus).processCommittedMessage(0xc000bd6000, 0x59400000005, 0x57f53198, 0xc001ed78e0, 0x20, 0x20, 0xc002a37400, 0x34, 0x40, 0xc003057aa0, ...)
 /home/ec2-user/go/src/github.com/harmony-one/harmony/consensus/consensus_validator.go:226 +0x4cc
github.com/harmony-one/harmony/consensus.(*Consensus).ProcessMessageValidator(0xc000bd6000, 0xc004b8efa1, 0x95, 0x95)
 /home/ec2-user/go/src/github.com/harmony-one/harmony/consensus/consensus_validator.go:56 +0xf1
github.com/harmony-one/harmony/node.(*Node).messageHandler(0xc0000a2240, 0xc004b8efa0, 0x96, 0x96, 0x0, 0x0)
 /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_handler.go:117 +0xf89
github.com/harmony-one/harmony/node.(*Node).StreamHandler(0xc0000a2240, 0x7fad187291c0, 0xc001ba1880)
 /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_handler.go:50 +0x22d
github.com/harmony-one/harmony/node.(*Node).StreamHandler-fm(0x7fad187291c0, 0xc001ba1880)
 /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node.go:234 +0x3e
github.com/harmony-one/harmony/p2p/host/hostv2.(*HostV2).BindHandlerAndServe.func1(0x1113900, 0xc001ba1880)
 /home/ec2-user/go/src/github.com/harmony-one/harmony/p2p/host/hostv2/hostv2.go:205 +0x67
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1(0xc001403d20, 0xe, 0x7fad18729190, 0xc001ba1880, 0x10247, 0xc000143890)
 /home/ec2-user/go/src/github.com/libp2p/go-libp2p/p2p/host/basic/basic_host.go:299 +0x9d
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
 /home/ec2-user/go/src/github.com/libp2p/go-libp2p/p2p/host/basic/basic_host.go:257 +0x6cb
2019/03/12 08:44:06 Command finished with error: exit status 2

**To Reproduce**
I started testnet and started wallet to generate transactions.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by LeoHChen** [comment]
This is fixed in bls. https://github.com/harmony-one/bls/commit/c72447dfa9abcebb6f5ca698a9c85cbffda8606f
