### ISSUE TITLE
node program crash in testnet

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#603]
**Describe the bug**

One node process was crashed during the testnet.  There is a new crash signature.

```
2019/03/19 07:26:55 Command running ./harmony [-ip 13.250.61.36 -port 9000 -log_folder ../tmp_log/log-20190319.072507 -bootnodes /ip4/54.213.43.194/tcp/9876/p2p/QmQayinFSgMMw5cSpDUiD9pQ2WeP6WNmGxpZ6ou3mdVFJX,/ip4/100.26.90.187/tcp/9876/p2p/QmZJJx6AdaoEkGLrYG4JeLCKeCKDjnFz2wfHNHxAqFSGA9 -min_peers 48 -is_beacon]
2019/03/19 21:13:05 Stderr 2019/03/19 07:26:55 No priviate key can be loaded from filekeyfile./.hmykey
2019/03/19 07:26:55 Using random private key
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x838ae1]

goroutine 320319 [running]:
github.com/harmony-one/harmony/core/types.(*Block).EncodeRLP(0x0, 0x11e4240, 0xc001d2eaf0, 0x7f9b1c7be9c0, 0x0)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/core/types/block.go:262 +0x41
github.com/ethereum/go-ethereum/rlp.writeEncoder(0xed9900, 0x0, 0x16, 0xc001d2eaf0, 0x0, 0x0)
        /home/ec2-user/go/src/github.com/ethereum/go-ethereum/rlp/encode.go:472 +0x97
github.com/ethereum/go-ethereum/rlp.(*encbuf).encode(0xc001d2eaf0, 0xed9900, 0x0, 0xe7b0e0, 0xc001d2eaf0)
        /home/ec2-user/go/src/github.com/ethereum/go-ethereum/rlp/encode.go:187 +0x135
github.com/ethereum/go-ethereum/rlp.EncodeToBytes(0xed9900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ec2-user/go/src/github.com/ethereum/go-ethereum/rlp/encode.go:101 +0xe4
github.com/harmony-one/harmony/node.(*Node).CalculateResponse(0xc000116840, 0xc002862d20, 0xdd5b40, 0xc001d2ea00, 0x11e4800)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node.go:353 +0x17a
github.com/harmony-one/harmony/api/service/syncing/downloader.(*Server).Query(0xc0000921e0, 0x11fb360, 0xc002790930, 0xc002862d20, 0xc0000921e0, 0xc002790930, 0xc001cddbd0)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/server.go:24 +0x3d
github.com/harmony-one/harmony/api/service/syncing/downloader/proto._Downloader_Query_Handler(0xdd5b40, 0xc0000921e0, 0x11fb360, 0xc002790930, 0xc001d2eaa0, 0x0, 0x11fb360, 0xc002790930, 0xc002a9f170, 0x24)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/proto/downloader.pb.go:288 +0x23e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0011db200, 0x1205560, 0xc002d98900, 0xc003546a00, 0xc002682480, 0x1adbed0, 0x0, 0x0, 0x0)
        /home/ec2-user/go/src/google.golang.org/grpc/server.go:966 +0x4b5
google.golang.org/grpc.(*Server).handleStream(0xc0011db200, 0x1205560, 0xc002d98900, 0xc003546a00, 0x0)
        /home/ec2-user/go/src/google.golang.org/grpc/server.go:1245 +0xd25
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc001265ef0, 0xc0011db200, 0x1205560, 0xc002d98900, 0xc003546a00)
        /home/ec2-user/go/src/google.golang.org/grpc/server.go:685 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/ec2-user/go/src/google.golang.org/grpc/server.go:683 +0xa1
2019/03/19 21:13:05 Command finished with error: exit status 2
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by LeoHChen** [comment]
fixed.
