### ISSUE TITLE
Panic on deserialize ping message

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#617]
**Describe the bug**

Panic reported in the external testnet node operator.

 r.ID QmL7oaM4> Addrs:[/ip4/52.51.38.220/tcp/9000]}"
2019/03/21 23:34:02 Can't deserialize Ping message
panic: Can't deserialize Ping message

goroutine 3880 [running]:
log.Panic(0xc0025dbcc0, 0x1, 0x1)
    /usr/local/go/src/log/log.go:333 +0xac
github.com/harmony-one/harmony/api/proto/discovery.GetPingMessage(0xc00129e007, 0xc5, 0xc9, 0xd69ac0, 0x1b32ce1, 0x0)
    /home/ec2-user/go/src/github.com/harmony-one/harmony/api/proto/discovery/pingpong.go:110 +0x115
github.com/harmony-one/harmony/node.(Node).pingMessageHandler(0xc0000ccdc0, 0xc00129e007, 0xc5, 0xc9, 0xc002472540, 0x22, 0x0)
    /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_handler.go:360 +0x6e
github.com/harmony-one/harmony/node.(Node).messageHandler(0xc0000ccdc0, 0xc00129e005, 0xc7, 0xcb, 0xc002472540, 0x22)
    /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_handler.go:186 +0x927
created by github.com/harmony-one/harmony/node.(Node).ReceiveGroupMessage
    /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_handler.go:47 +0x177

**Comment by LeoHChen** [comment]
fixed.
