### ISSUE TITLE
invalid opcode 0x1b

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#631]
**Describe the bug**

I was testing my pong message code using my pong_message_not_sent branch and when I run deploy.sh test locally, I hit the following errors.
```
WARN [03-23|01:09:28.771] No new block is received so far          port=19999 ip=127.0.0.1
DEBUG[03-23|01:09:36.449] PROPOSING NEW BLOCK ------------------------------------------------ port=9000 ip=127.0.0.1 threshold=2 pendingTransactions=103
DEBUG[03-23|01:09:36.451] VM returned with error                   err="invalid opcode 0x1b"
DEBUG[03-23|01:09:36.598] Selecting Transactions                   port=9000 ip=127.0.0.1 remainPending=0 selected=103 invalidDiscarded=0
DEBUG[03-23|01:09:36.598] VM returned with error                   err="invalid opcode 0x1b"
WARN [03-23|01:09:38.774] No new block is received so far          port=19999 ip=127.0.0.1

```
**To Reproduce**
1. Check out code with "invalid_opcode_0x1b" commit
2. Build
3. run local test using "...." commands

test/deploy.sh test/configs/oneshard1.txt

**Expected behavior**

Consensus reached

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by LeoHChen** [comment]
extra logs.

```
DEBUG[03-23|01:34:47.623] Inserted new block                       number=1 hash=10f33f…87c306 uncles=0 txs=103 ERROR[03-23|01:34:47.612] [ABI] Failed executing the transaction   port=9010 ip=127.0.0.1 error=
nil
ERROR[03-23|01:34:47.612] Failed to unpack stake info              port=9010 ip=127.0.0.1 error="abi: unmarshalling empty output"
DEBUG[03-23|01:34:47.615] [SYNC] peerRegistration Record           port=9010 ip=127.0.0.1 selfPeerAddress=0xB1a331EdC0Bec4C25Dc94f9a9551Fc048C87eC7C number=0
gas=3958675 elapsed=243.830ms
INFO [03-23|01:34:47.623] Imported new chain segment               blocks=1 txs=103 mgas=3.959 elapsed=244.045ms mgasps=16.221 number=1 hash=10f33f…87c306 cache=76.68kB
INFO [03-23|01:34:47.623] adding new block to blockchain           port=9003 ip=127.0.0.1 blockNum=0 by node="127.0.0.1:9003/<peer.ID Qm*gzm4AC>[0]"
INFO [03-23|01:34:47.624] Updating staking list                    port=9003 ip=127.0.0.1
INFO [03-23|01:34:47.636] NET: received message: Node/Block        port=9011 ip=127.0.0.1
INFO [03-23|01:34:47.636] NET: received message: Node/Sync         port=9011 ip=127.0.0.1
INFO [0INFO [03-23|01:34:47.637] NET: received message: Node/Block        port=19999 ip=127.0.0.1
INFO [03-23|01:34:47.637] NET: received message: Node/Sync         port=19999 ip=127.0.0.1
INFO [03-23|01:34:47.637] Block being handled by client by         port=19999 ip=127.0.0.1 self peer="127.0.0.1:19999/<peer.ID Qm*MTzBmV>[0]"
INFO [03-23|01:34:47.637] [Txgen] Received new block               port=19999 ip=127.0.0.1 block=[0xc0034f6090]
INFO [03-23|01:34:47.637] Current Block                            port=19999 ip=127.0.0.1 hash=0x811737e250857a0faaacefcd94e066ef01a8adede7873d8cd3a8104edd291a56
INFO [03-23|01:34:47.638] Adding block from leader                 port=19999 ip=127.0.0.1 txNum=103 shardID=0 preHash=0x811737e250857a0faaacefcd94e066ef01a8adede7873d8cd3a8104edd291a56
DEBUG[03-23|01:34:47.640] VM returned with error                   err="invalid opcode 0x1b"
ERROR[03-23|01:34:47.601] [ABI] Failed executing the transaction   port=9007 ip=127.0.0.1 error=nil
ERROR[03-23|01:34:47.601] Failed to unpack stake info              port=9007 ip=127.0.0.1 error="abi: unmarshalling empty output"
DEBUG[03-23|01:34:47.601] [SYNC] peerRegistration Record           port=9007 ip=127.0.0.1 selfPeerAddress=0x7498F0c3CB7FF1fd8E95794C3b3E9e8285001339 number=0
3-23|01:34:47.637] Block being handled by block channel     port=9011 ip=127.0.0.1 self peer="127.0.0.1:9011/<peer.ID Qm*skyD5g>[0]"
DEBUG[03-23|01:34:47.637] CreateSyncConfig: len of peers           port=9011 ip=127.0.0.1 len=0
WARN [03-23|01:34:47.637] [SYNC] Unable to get neighbor peers      port=9011 ip=127.0.0.1
DEBUG[03-23|01:34:47.605] Inserted new block                       number=1 hash=10f33f…87c306 uncles=0 txs=103 gas=3958675 elapsed=227.790ms
INFO [03-23|01:34:47.605] Imported new chain segment               blocks=1 txs=103 mgas=3.959 elapsed=227.995ms mgasps=17.363 number=1 hash=10f33f…87c306 cache=76.68kB
INFO [03-23|01:34:47.605] adding new block to blockchain           port=9002 ip=127.0.0.1 blockNum=0 by node="127.0.0.1:9002/<peer.ID Qm*QRSsfN>[0]"
INFO [03-23|01:34:47.605] Updating staking list                    port=9002 ip=127.0.0.1
DEBUG[03-23|01:34:47.608] VM returned with error                   err="invalid opcode 0x1c"
ERROR[03-23|01:34:47.608] [ABI] Failed executing the transaction   port=9002 ip=127.0.0.1 error=nil
ERROR[03-23|01:34:47.608] Failed to unpack stake info              port=9002 ip=127.0.0.1 error="abi: unmarshalling empty output"
DEBUG[03-23|01:34:47.608] [SYNC] peerRegistration Record           port=9002 ip=127.0.0.1 selfPeerAddress=0xE6F1ed9a50697B0892D33eAF96A1278e19aB9295 number=0
DEBUG[03-23|01:34:47.649] VM returned with error                   err="invalid opcode 0x1b"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4719c1b]

goroutine 1139 [running]:
github.com/harmony-one/harmony/api/service/syncing.(*StateSync).MakeConnectionToPeers(0xc00377e240)
        /Users/leochen/work/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:175 +0x5b
github.com/harmony-one/harmony/node.(*Node).DoBeaconSyncing(0xc000134000)
        /Users/leochen/work/go/src/github.com/harmony-one/harmony/node/node_syncing.go:72 +0x38d
created by main.main
        /Users/leochen/work/go/src/github.com/harmony-one/harmony/cmd/harmony/main.go:267 +0x713
DEBUG[03-23|01:34:47.652] VM returned with error                   err="invalid opcode 0x1c"
ERROR[03-23|01:34:47.653] [ABI] Failed executing the transaction   port=9009 ip=127.0.0.1 error=nil
ERROR[03-23|01:34:47.653] Failed to unpack stake info              port=9009 ip=127.0.0.1 error="abi: unmarshalling empty output"
DEBUG[03-23|01:34:47.653] [SYNC] peerRegistration Record           port=9009 ip=127.0.0.1 selfPeerAddress=0x13733cB20E96f13Fc5D9B8708614a9E87b55A278 number=0
DEBUG[03-23|01:34:47.657] VM returned with error                   err="invalid opcode 0x1c"
```

**Comment by chaosma** [comment]
The latest master branch refactored the beacon sync.  I tested with the latest master branch, the error not show up anymore
