### ISSUE TITLE
integer divide by zero crash

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#675]
**Describe the bug**

On latest banjo branch, launched test net and git the following errors on the validators.

```
2019/04/02 04:29:02 Command running ./harmony [-ip 52.208.78.188 -port 9000 -log_folder ../tmp_log/log-20190402.042758 -bootnodes /ip4/54.213.43.194/tcp/9876/p2p/QmQayinFSgMMw5cSpDUiD9pQ2WeP6WNmGxpZ6ou3mdVFJX,/ip4/100.26.90.187/tcp/9876/p2p/QmZJJx6AdaoEkGLrYG4JeLCKeCKDjnFz2wfHNHxAqFSGA9 -min_peers 36 -is_beacon -account_index 48]
2019/04/02 04:47:42 Stderr 2019/04/02 04:29:02 No priviate key can be loaded from filekeyfile./.hmykey
2019/04/02 04:29:02 Using random private key
panic: runtime error: integer divide by zero

goroutine 27944 [running]:
github.com/harmony-one/harmony/core.(*ShardingState).assignNewNodes(0xc0048a9dd0, 0xc00516a800, 0x32, 0x40)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/core/resharding.go:57 +0x28b
github.com/harmony-one/harmony/core.(*ShardingState).Reshard(0xc0048a9dd0, 0xc00516a800, 0x32, 0x40, 0x3fb999999999999a)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/core/resharding.go:108 +0x88
github.com/harmony-one/harmony/core.CalculateNewShardState(0xc002ce6000, 0x7, 0xc00003c1c8, 0x1a64b96163ecf822, 0x1215050672bb47fa, 0x46)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/core/resharding.go:169 +0x7e8
github.com/harmony-one/harmony/core.(*BlockChain).GetNewShardState(0xc002ce6000, 0xc002cda090, 0xc00003c1c8, 0xc003c318d8, 0x411b28, 0xc001daa1e0)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/core/blockchain.go:1716 +0x15b
github.com/harmony-one/harmony/core.(*BlockChain).StoreNewShardState(0xc002ce6000, 0xc002cda090, 0xc00003c1c8, 0x0, 0x0, 0x0)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/core/blockchain.go:1738 +0x5d
github.com/harmony-one/harmony/node.(*Node).PostConsensusProcessing(0xc00003c000, 0xc002cda090)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_handler.go:312 +0x1d1
github.com/harmony-one/harmony/consensus.(*Consensus).processCommittedMessage(0xc0000e2900, 0xc003940a80)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/consensus/consensus_validator.go:263 +0xe38
github.com/harmony-one/harmony/consensus.(*Consensus).ProcessMessageValidator(0xc0000e2900, 0xc0014a3906, 0xf7, 0xfa)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/consensus/consensus_validator.go:40 +0x287
github.com/harmony-one/harmony/node.(*Node).messageHandler(0xc00003c000, 0xc0014a3905, 0xf8, 0xfb, 0xc004c5aea0, 0x22)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_handler.go:105 +0xfa6
created by github.com/harmony-one/harmony/node.(*Node).ReceiveGroupMessage
        /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_handler.go:48 +0x177
2019/04/02 04:47:42 Command finished with error: exit status 2
```

3 out of 50 nodes hit the same errors.  The log is available at s3://harmony-benchmark/logs/20190402.042758

**Comment by harmony-ek** [comment]
On it.

**Comment by harmony-ek** [comment]
Findings so far (for @chaosma's information):

The offending line is a modulus operation in `assignNewNodes()`:
```go
// assignNewNodes add new nodes into the N/2 active committees evenly
func (ss *ShardingState) assignNewNodes(newNodeList []types.NodeID) {
	ss.sortCommitteeBySize()
	numActiveShards := ss.numShards / 2
	Shuffle(newNodeList)
	for i, nid := range newNodeList {
		id := i % numActiveShards
		ss.shardState[id].NodeList = append(ss.shardState[id].NodeList, nid)
	}
}
```
Since `numActiveShards` to be 0, `ss.numShards` is 0 or 1.  The field is initialized here:

```go
// GetShardingStateFromBlockChain will retrieve random seed and shard map from beacon chain for given a epoch
func GetShardingStateFromBlockChain(bc *BlockChain, epoch uint64) *ShardingState {
	number := GetBlockNumberFromEpoch(epoch)
	shardState := bc.GetShardStateByNumber(number)

	rndSeedBytes := bc.GetRandSeedByNumber(number)
	rndSeed := binary.BigEndian.Uint64(rndSeedBytes[:])

	return &ShardingState{epoch: epoch, rnd: rndSeed, shardState: shardState, numShards: len(shardState)}
}
```

(`GetShardingStateFromBlockChain()` is called from `CalculateNewShardState()` (3rd frame in the stack trace), to get the previous shard state.)

In order for `ss.numShards: len(shardState)` to be 0 or 1, `shardState` should be an empty slice (potentially `nil`), or less likely, should contain exactly one shard.

My hunch is that the former is the case, especially `shardState == nil`, which may happen if `bc.GetShardStateByNumber(number)` returned `nil` to signal that the given epoch block (in this case, one for the previous epoch) is not found in the database.

@chaosma, a few questions for you:

1. Does the above make sense to you?
2. Do we have a mechanism to ensure that the epoch block for the previous epoch is in the database before we try to enter a new epoch (which seems to be happening here)?

**Comment by harmony-ek** [comment]
Also @rlan35's input would be appreciated.

In the short term, we should at least check for and handle `nil` return values.  On it.

**Comment by harmony-ek** [comment]
`nil` check (#679) has been merged.  This should eliminate use of nil `shardState`, which was causing this issue.  Closing.

**Comment by LeoHChen** [comment]
When ss.numShards == 1, we still have the divide by zero crash.

**Comment by LeoHChen** [comment]
should be fixed in https://github.com/harmony-one/harmony/pull/722, and cherry-picked in banjo.
