### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#676]
**Describe the bug**

On the recently launched testnet using Banjo branch, the following bug was found that crashed the node.

```
panic: runtime error: index out of range

goroutine 474038 [running]:
github.com/harmony-one/harmony/api/service/syncing.(*StateSync).RegisterNodeInfo(0xc0014b2200, 0xc003d720a0)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:547 +0xa5a
github.com/harmony-one/harmony/node.(*Node).CalculateResponse(0xc0000fe000, 0xc005e587e0, 0xdd4340, 0xc003d72000, 0x11efb80)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_syncing.go:243 +0xb0e
github.com/harmony-one/harmony/api/service/syncing/downloader.(*Server).Query(0xc0001f6070, 0x12068e0, 0xc001d9fef0, 0xc005e587e0, 0xc0001f6070, 0xc001d9fef0, 0xc00585abd0)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/server.go:24 +0x3d
github.com/harmony-one/harmony/api/service/syncing/downloader/proto._Downloader_Query_Handler(0xdd4340, 0xc0001f6070, 0x12068e0, 0xc001d9fef0, 0xc003d72000, 0x0, 0x12068e0, 0xc001d9fef0, 0xc00375e480, 0x41c)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/downloader/proto/downloader.pb.go:318 +0x23e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001180480, 0x1210960, 0xc005c5d200, 0xc0024c4200, 0xc00267c450, 0x1addd90, 0x0, 0x0, 0x0)
        /home/ec2-user/go/pkg/mod/google.golang.org/grpc@v1.19.0/server.go:971 +0x4b5
google.golang.org/grpc.(*Server).handleStream(0xc001180480, 0x1210960, 0xc005c5d200, 0xc0024c4200, 0x0)
        /home/ec2-user/go/pkg/mod/google.golang.org/grpc@v1.19.0/server.go:1250 +0xd25
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc005b295e0, 0xc001180480, 0x1210960, 0xc005c5d200, 0xc0024c4200)
        /home/ec2-user/go/pkg/mod/google.golang.org/grpc@v1.19.0/server.go:690 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/ec2-user/go/pkg/mod/google.golang.org/grpc@v1.19.0/server.go:688 +0xa1
```

**Comment by harmony-ek** [comment]
On it.

**Comment by harmony-ek** [comment]
The offending line is “`peerConfig := ss.syncConfig.peers[id]`” in `StateSync.RegisterNodeInfo()`:

```go
// RegisterNodeInfo will register node to peers to accept future new block broadcasting
// return number of successfull registration
func (ss *StateSync) RegisterNodeInfo() int {
	ss.CleanUpNilPeers()
	registrationNumber := RegistrationNumber
	utils.GetLogInstance().Debug("[SYNC] node registration to peers", "registrationNumber", registrationNumber, "activePeerNumber", ss.activePeerNumber)

	count := 0
	for id := range ss.syncConfig.peers {
		peerConfig := ss.syncConfig.peers[id]
		if count >= registrationNumber {
			break
		}
		if peerConfig.ip == ss.selfip && peerConfig.port == GetSyncingPort(ss.selfport) {
			utils.GetLogInstance().Debug("[SYNC] skip self", "peerport", peerConfig.port, "selfport", ss.selfport, "selfsyncport", GetSyncingPort(ss.selfport))
			continue
		}
		if peerConfig.client == nil {
			continue
		}
		err := peerConfig.registerToBroadcast(ss.selfPeerHash[:], ss.selfip, ss.selfport)
		if err != nil {
			utils.GetLogInstance().Debug("[SYNC] register failed to peer", "ip", peerConfig.ip, "port", peerConfig.port, "selfPeerHash", ss.selfPeerHash)
			continue
		}
		utils.GetLogInstance().Debug("[SYNC] register success", "ip", peerConfig.ip, "port", peerConfig.port)
		count++
	}
	return count
}
```

This could happen if the source of range (`ss.syncConfig.peers`) were modified while iterating.  To demonstrates:

```go
package main

import "fmt"

func main() {
	a := []int{3, 4, 5}
	for i := range a {
		fmt.Printf("a[i] = %+v\n", a[i])
		a = a[:0]
	}
}
```

Checking to see why the range source is being modified.

**Comment by harmony-ek** [comment]
`SyncConfig.peers` is modified (after initialization) only in one place: `SyncConfig.CleanUpPeers()` may shorten the list by removing peers with mismatching block hash while maintaining order.  The only possible call chain is:

```
SyncConfig.CleanupPeers()
StateSync.GetBlockHashesConsensusAndCleanUp()
StateSync.GetConsensusHashes()
StateSync.ProcessStateSync()
StateSync.SyncLoop()
StateSync.DoSyncing()
```

The last one (`DoSyncing`) is its own goroutine, separate from the one shown in the panic trace.  This evidences that it is a race condition.

Next step: Guard peers using mutex.

**Comment by LeoHChen** [comment]
Seen this again on testnet.  One node crashed.

**Comment by LeoHChen** [comment]
Is there a quick patch?

**Comment by LeoHChen** [comment]
The problem can be resolved using sync.Map.

https://godoc.org/golang.org/x/sync/syncmap

We are using it already in consensus.

**Comment by LeoHChen** [comment]
@chaosma , can you submit a fix today?

**Comment by chaosma** [comment]
The code that modify the list is CleanUpPeers function. When the blockhashes not match, it will try to clean up peers that not the same as majority. The name of CleanUpNilPeers is kind of misleading, we could remove the peer where the connection is nil in CleanUpNilPeers.
