### ISSUE TITLE
index out of range calling getFreeToken

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#694]
**Describe the bug**

leader node crash after receiving a getFreeToken call. This is on devnet, master branch.

**To Reproduce**

1. launched a devnet using 4shards profile
2. call getFreeToken using wallet
3. one leader crashed with the following crash dump.

```
2019/04/08 21:34:50 Stderr 2019/04/08 20:57:07 No priviate key can be loaded from filekeyfile./.hmykey
2019/04/08 20:57:07 Using random private key
panic: runtime error: index out of range

goroutine 32459 [running]:
github.com/harmony-one/harmony/node.(*Node).callGetFreeTokenWithNonce(0xc0000e8000, 0x7ca9d84f93183418, 0xdfb217131586e098, 0xc0a8b85962, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/leochen/go/src/github.com/harmony-one/harmony/node/contract.go:169 +0x752
github.com/harmony-one/harmony/node.(*Node).callGetFreeToken(0xc0000e8000, 0x7ca9d84f93183418, 0xdfb217131586e098, 0x7f0ca8b85962, 0x0, 0x0, 0x0, 0x0)
        /home/leochen/go/src/github.com/harmony-one/harmony/node/contract.go:157 +0xc9
github.com/harmony-one/harmony/node.(*Node).CallFaucetContract(...)
        /home/leochen/go/src/github.com/harmony-one/harmony/node/contract.go:152
github.com/harmony-one/harmony/api/client/service.(*Server).GetFreeToken(0xc003057a40, 0x120e740, 0xc003ff4fc0, 0xc00382fe40, 0xc003057a40, 0xc003ff4fc0, 0xc002e42bd0)
        /home/leochen/go/src/github.com/harmony-one/harmony/api/client/service/server.go:38 +0xd9
github.com/harmony-one/harmony/api/client/service/proto._ClientService_GetFreeToken_Handler(0xe0d8a0, 0xc003057a40, 0x120e740, 0xc003ff4fc0, 0xc004e54be0, 0x0, 0x120e740, 0xc003ff4fc0, 0xc00272c360, 0x16)
        /home/leochen/go/src/github.com/harmony-one/harmony/api/client/service/proto/client.pb.go:419 +0x23e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00131f380, 0x12187c0, 0xc004f6d080, 0xc0000a7a00, 0xc003241da0, 0x1aef658, 0x0, 0x0, 0x0)
        /home/leochen/go/pkg/mod/google.golang.org/grpc@v1.19.0/server.go:971 +0x470
google.golang.org/grpc.(*Server).handleStream(0xc00131f380, 0x12187c0, 0xc004f6d080, 0xc0000a7a00, 0x0)
        /home/leochen/go/pkg/mod/google.golang.org/grpc@v1.19.0/server.go:1250 +0xd25
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0011debf0, 0xc00131f380, 0x12187c0, 0xc004f6d080, 0xc0000a7a00)
        /home/leochen/go/pkg/mod/google.golang.org/grpc@v1.19.0/server.go:690 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/leochen/go/pkg/mod/google.golang.org/grpc@v1.19.0/server.go:688 +0xa1
2019/04/08 21:34:50 Command finished with error: exit status 2

```

**Expected behavior**
Leader shouldn't crash.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by LeoHChen** [comment]
This is not a beacon chain shard.  This is a regular shard.

**Comment by LeoHChen** [comment]
This is not a testnet blocker.  But we shouldn't crash anyway.

**Comment by LeoHChen** [comment]
fixed.
