### ISSUE TITLE
Yet another index out of range issue

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#703]
**Describe the bug**

Found another index out of range in syncing code on testnet.
```
2019/04/09 22:59:00 Using random private key
panic: runtime error: index out of range

goroutine 3439499 [running]:
github.com/harmony-one/harmony/api/service/syncing.(*StateSync).downloadBlocks.func1.1(0xc005089ca0, 0xc0036dfea0, 0xc00342a280, 0xc005089cb0, 0xc005027380, 0xc00001a000)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:365 +0x74a
created by github.com/harmony-one/harmony/api/service/syncing.(*StateSync).downloadBlocks.func1
        /home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/syncing/syncing.go:342 +0xaa
2019/04/10 10:27:27 Command finished with error: exit status 2

```

**Comment by LeoHChen** [comment]
fixed
