### ISSUE TITLE
crash: nil pointer deference in wallet

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#725]
**Describe the bug**

Running wallet on a newly launched 1+3 devnet, using the beat_tx.sh script.  Wallet hit a sigsegv fault.

The log is like:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x170 pc=0xbdab62]

goroutine 2226 [running]:
github.com/harmony-one/harmony/node.(*Node).epochShardStateMessageHandler(0xc0002fa000, 0xc000672007, 0x98e1, 0x9ff9, 0xc00055fe50)
        /home/leochen/go/src/github.com/harmony-one/harmony/node/node_handler.go:544 +0x62
github.com/harmony-one/harmony/node.(*Node).messageHandler(0xc0002fa000, 0xc000672005, 0x98e3, 0x9ffb, 0xc0000b36b0, 0x22)
        /home/leochen/go/src/github.com/harmony-one/harmony/node/node_handler.go:193 +0xf31
created by github.com/harmony-one/harmony/node.(*Node).ReceiveClientGroupMessage
        /home/leochen/go/src/github.com/harmony-one/harmony/node/node_handler.go:70 +0x31e
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x170 pc=0xbdab62]
```

**Comment by LeoHChen** [comment]
fixed in https://github.com/harmony-one/harmony/pull/727
