### ISSUE TITLE
index out of range crash

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#744]
**Describe the bug**

panic: runtime error: index out of range

goroutine 313194 [running]:
github.com/harmony-one/harmony/core.(*ShardingState).assignNewNodes(0xc0047b97d8, 0xc004d08000, 0x32, 0x40)
   /home/ec2-user/go/src/github.com/harmony-one/harmony/core/resharding.go:62 +0x291
github.com/harmony-one/harmony/core.(*ShardingState).Reshard(0xc0047b97d8, 0xc004d08000, 0x32, 0x40, 0x3fb999999999999a)
   /home/ec2-user/go/src/github.com/harmony-one/harmony/core/resharding.go:115 +0x88
github.com/harmony-one/harmony/core.CalculateNewShardState(0xc001da2000, 0xc, 0xc00010a1c8, 0xc002551940, 0x4, 0x4)
   /home/ec2-user/go/src/github.com/harmony-one/harmony/core/resharding.go:199 +0x7f4
github.com/harmony-one/harmony/core.(*BlockChain).GetNewShardState(0xc001da2000, 0xc0032f0510, 0xc00010a1c8, 0xc00228ed80, 0xc00228eda0, 0xc0025518c0)
   /home/ec2-user/go/src/github.com/harmony-one/harmony/core/blockchain.go:1726 +0x2b4
github.com/harmony-one/harmony/core.(*BlockChain).StoreNewShardState(0xc001da2000, 0xc0032f0510, 0xc00010a1c8, 0x0, 0x0, 0x0)
   /home/ec2-user/go/src/github.com/harmony-one/harmony/core/blockchain.go:1748 +0x5a
github.com/harmony-one/harmony/node.(*Node).PostConsensusProcessing(0xc00010a000, 0xc0032f0510)
   /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_handler.go:312 +0x1d1
github.com/harmony-one/harmony/consensus.(*Consensus).processCommittedMessage(0xc0000ca900, 0xc0023a24e0)
   /home/ec2-user/go/src/github.com/harmony-one/harmony/consensus/consensus_validator.go:263 +0xe38
github.com/harmony-one/harmony/consensus.(*Consensus).ProcessMessageValidator(0xc0000ca900, 0xc000dd5206, 0xf8, 0xfa)
   /home/ec2-user/go/src/github.com/harmony-one/harmony/consensus/consensus_validator.go:40 +0x287
github.com/harmony-one/harmony/node.(*Node).messageHandler(0xc00010a000, 0xc000dd5205, 0xf9, 0xfb, 0xc003f95b00, 0x22)
   /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_handler.go:105 +0xfa6
created by github.com/harmony-one/harmony/node.(*Node).ReceiveGroupMessage
   /home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_handler.go:48 +0x177
2019/04/16 17:24:44 Command finished with error: exit status 2

**Comment by LeoHChen** [comment]
we will fix it in master branch.
