### ISSUE TITLE
[crash] nil pointer deference in demo contract

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#759]
**Describe the bug**

The banjo testnet got a crash with the following stack trace.

```
2019/04/20 00:02:50 http: panic serving 35.225.9.151:45906: runtime error: invalid memory address or nil pointer dereference
goroutine 529131 [running]:
net/http.(*conn).serve.func1(0xc003f8c0a0)
        /usr/local/go/src/net/http/server.go:1769 +0xc9
panic(0xdd1200, 0x1adebf0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/harmony-one/harmony/node.(*Node).CreateTransactionForPickWinner(0xc0025c2300, 0xc00250c101, 0xc002398900)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/node/demo_contract.go:184 +0x461
github.com/harmony-one/harmony/api/service/restclientsupport.(*Service).Winner(0xc00001e4b0, 0x1204b20, 0xc0042f9b20, 0xc00301d700)
        /home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/restclientsupport/service.go:156 +0x1b5
```

**Comment by LeoHChen** [comment]
fixed.
