### ISSUE TITLE
concurrent map writes error

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#837]
**Describe the bug**

Got a crash on leader with concurrent map write error.

```
fatal error: concurrent map writes

goroutine 1437640 [running]:
runtime.throw(0xf6e76d, 0x15)
        /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc00a7155c0 sp=0xc00a715590 pc=0x432c92
runtime.mapassign(0xe0c060, 0xc001af3a10, 0xc00a715674, 0x1dd9f415)
        /usr/local/go/src/runtime/map.go:682 +0x5c8 fp=0xc00a715648 sp=0xc00a7155c0 pc=0x4139a8
github.com/harmony-one/harmony/node.(*Node).GetAndIncreaseAddressNonce(0xc000100000, 0x4d2733129131ba4a, 0x1ea642b7dcca1b38, 0x1dd9f415, 0x0)
        /home/leochen/go/src/github.com/harmony-one/harmony/node/puzzle_contract.go:222 +0xfe fp=0xc00a7156a0 sp=0xc00a715648 pc=0xc4e29e
github.com/harmony-one/harmony/node.(*Node).CreateTransactionForPayoutMethod(0xc000100000, 0xc002b7f120, 0x40, 0x8, 0xc002b7f172, 0x2, 0x50, 0xebf300, 0xc008c84201, 0xc00d0f5cc0)
        /home/leochen/go/src/github.com/harmony-one/harmony/node/puzzle_contract.go:139 +0x851 fp=0xc00a7158f8 sp=0xc00a7156a0 pc=0xc4d301
github.com/harmony-one/harmony/node.(*Node).CreateTransactionForPayoutMethod-fm(0xc002b7f120, 0x40, 0x8, 0xc002b7f172, 0x2, 0x59, 0x0, 0x0, 0xa141b8)
        /home/leochen/go/src/github.com/harmony-one/harmony/node/puzzle_contract.go:111 +0x63 fp=0xc00a715958 sp=0xc00a7158f8 pc=0xc53743
github.com/harmony-one/harmony/api/service/restclientsupport.(*Service).Payout(0xc002df8540, 0x1275f20, 0xc005a38d20, 0xc012439f00)
        /home/leochen/go/src/github.com/harmony-one/harmony/api/service/restclientsupport/puzzle_service.go:62 +0x370 fp=0xc00a715b68 sp=0xc00a715958 pc=0xc2ca80
github.com/harmony-one/harmony/api/service/restclientsupport.(*Service).Payout-fm(0x1275f20, 0xc005a38d20, 0xc012439f00)
        /home/leochen/go/src/github.com/harmony-one/harmony/api/service/restclientsupport/puzzle_service.go:46 +0x48 fp=0xc00a715b98 sp=0xc00a715b68 pc=0xc30e58
net/http.HandlerFunc.ServeHTTP(0xc002cc0c60, 0x1275f20, 0xc005a38d20, 0xc012439f00)
        /usr/local/go/src/net/http/server.go:1995 +0x44 fp=0xc00a715bc0 sp=0xc00a715b98 pc=0x919c54
github.com/gorilla/mux.(*Router).ServeHTTP(0xc002e04600, 0x1275f20, 0xc005a38d20, 0xc007f8d800)
        /home/leochen/go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212 +0xe3 fp=0xc00a715cf0 sp=0xc00a715bc0 pc=0xa0e533
net/http.serverHandler.ServeHTTP(0xc002dfca90, 0x1275f20, 0xc005a38d20, 0xc007f8d800)
        /usr/local/go/src/net/http/server.go:2774 +0xa8 fp=0xc00a715d20 sp=0xc00a715cf0 pc=0x91cf28
net/http.(*conn).serve(0xc0058439a0, 0x1279120, 0xc002f49740)
        /usr/local/go/src/net/http/server.go:1878 +0x851 fp=0xc00a715fc8 sp=0xc00a715d20 pc=0x918c11
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00a715fd0 sp=0xc00a715fc8 pc=0x45fe61
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2884 +0x2f4

```

**Comment by LeoHChen** [comment]
fixed
